### ISSUE TITLE
Hide icons option

### ISSUE THREAD

**Issue by WesCossick** [sparksuite/simplemde-markdown-editor#105]
Create a new option called `hideIcons` that accepts an array of icons to hide.

That way, users can hide one or two of the default icons without having to customize the entire toolbar. Allows new buttons to appear when updates occur, along with any default order changes.

**Comment by WesCossick** [comment]
Done.

**Comment by christianmalek** [comment]
An option to hide every icon without explicitly naming them would be great if the editor will be used for a preview only mode.

edit:

Forget it. I just saw the `toolbar` property.
