### ISSUE TITLE
Possibly change from marked to remarkable?

### ISSUE THREAD

**Issue by WesCossick** [sparksuite/simplemde-markdown-editor#106]
[Remarkable](https://github.com/jonschlinkert/remarkable) looks to have better options, more features, CommonMark support, etc. Consider using this as the built in Markdown compiler for previewing.

**Comment by Kilerd** [comment]
I use CommonMark in my website.
I don't like a big markdown editor, so the common function is ok.
So, in my opinion, don't import too many thing in this editor.

**Comment by WesCossick** [comment]
I do see that remarkable's min file is 93.7 KB vs marked's 19.1 KB. Not sure if it's possible to trim it down, but it would be bundled into SimpleMDE and it would replace marked.

**Comment by trousev** [comment]
+1 for this. It will be very nice to use simpleMDE for CommonMark.
