### ISSUE TITLE
Prevent files from being dropped in edit area

### ISSUE THREAD

**Issue by nivv** [sparksuite/simplemde-markdown-editor#108]
You can drop a file into the edit area, you can see the result in the attached screenshot. My opinion is that this shouldn't be possible

![skarmklipp 2015-09-18 11 29 37](https://cloud.githubusercontent.com/assets/4033930/9956391/a09fc60c-5df8-11e5-97a1-20c312e88e34.png)

**Comment by WesCossick** [comment]
Never thought to try that, good catch! I've added it to the next milestone.

**Comment by nivv** [comment]
Sweet! I noticed it since I had a dnd file upload with the drop target set to the body :) Thanks for quick the response :+1:

**Comment by WesCossick** [comment]
Created a PR in CodeMirror that adds a new option to fix this in SimpleMDE. Once it's been merged, this bug will no longer occur.

https://github.com/codemirror/CodeMirror/pull/3550
