### ISSUE TITLE
Organize global varables, function into an namespace?

### ISSUE THREAD

**Issue by thecreation** [sparksuite/simplemde-markdown-editor#112]
Hi,
I saw in simplemde.js file, there are some global varables (eg. isMac, shortcuts, saved_overflow) and some global functions (eg. toggleFullScreen, toggleBold, toggleItalic ...) . Can you organize them into a object? So it will not conlicts with other javascript plugins.

Thank you.
Best Regards

**Comment by WesCossick** [comment]
I'll look into doing this.

**Comment by Psychokrameur** [comment]
Hi,
+1 for @amazingSurge proposal.
This is a good (not to say "must have") best practice to avoid collision.

Thanks in advance

**Comment by WesCossick** [comment]
With PR #127, SimpleMDE now follows UMD design, which accomplishes this request. Thanks for the feedback.

**Comment by Psychokrameur** [comment]
Hello,

I'm not fully familiar with Github yet but I did not found where the change happen.

I did not see the global function / variable into a namespace, neither:
here : https://github.com/NextStepWebs/simplemde-markdown-editor/blob/master/src/js/simplemde.js
or here : https://github.com/NextStepWebs/simplemde-markdown-editor/blob/development/src/js/simplemde.js

Or maybe we not taking about the same thing :)

**Comment by WesCossick** [comment]
When Browserify compiles the code into one file, it handles the process. With the minified distribution files, you can no longer access the previously global variables and functions outside of the file. This is only on the development branch right now.

**Comment by Psychokrameur** [comment]
Ok... so only via a "browserify" process... which I don't know at all
that's why I did not find.

2015-10-20 21:02 GMT+02:00 Wes Cossick notifications@github.com:
