### ISSUE TITLE
Parts of text are randomly formatted as links

### ISSUE THREAD

**Issue by mzabsky** [sparksuite/simplemde-markdown-editor#113]
I noticed that parts of almost any text that I attempt to format using SimpleMDE are for some reason reason formatted as links - with gray font and underline. This also happens using the web demo, so it is not caused by my stylesheet or a library conflict, as I initially suspected.

It happens with following text:
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

![screenshot](https://cloud.githubusercontent.com/assets/1764281/10086906/36b45960-6311-11e5-8e1c-43f979ee7715.PNG)

**Comment by erlingur** [comment]
Yup, same here! Noticed it first with the word `nice`. Played around with it and it seems to have something to do with `i` being the first or second letter.

**Comment by erlingur** [comment]
It's fixed in the latest version: https://github.com/NextStepWebs/simplemde-markdown-editor/issues/111#issuecomment-142040454

**Comment by WesCossick** [comment]
Yep, it'll be fixed soon! See the other issue for the latest updates.
