### ISSUE TITLE
Preview Toggle

### ISSUE THREAD

**Issue by Xarcell** [sparksuite/simplemde-markdown-editor#116]
I like the preview toggle, but I don't like that it forces fullscreen. Can you change it so that it shows preview without going fullscreen?

This is a very sharp editor by the way. Well done.

**Comment by WesCossick** [comment]
Are you referring to the side by side preview toggle forcing fullscreen?

**Comment by Xarcell** [comment]
Yes sir.

**Comment by WesCossick** [comment]
Duplicate of #90
