### ISSUE TITLE
Bower/Browserify support

### ISSUE THREAD

**Issue by hardware** [sparksuite/simplemde-markdown-editor#118]
Hi,

Simplemde isn't available in bower or compatible with Browserify, why NPM ?
 It's a front-end package, not backend.

**Comment by WesCossick** [comment]
NPM is used to install both front-end and back-end packages, whether you're using Node.js or not. You can submit a PR that adds support for bower and/or broswerify if you'd like.

**Comment by hardware** [comment]
how to access assets files with the browser through node_modules directory ?

**Comment by WesCossick** [comment]
When you use `npm install` it downloads the entire repository to your local machine, in a folder called `node_modules`. Just go to SimpleMDE's directory in that folder and include the two files from the `/dist/` folder.

**Comment by hardware** [comment]
Ok, thanks.
