### ISSUE TITLE
Form submitting when pressing enter in Textarea

### ISSUE THREAD

**Issue by hardware** [sparksuite/simplemde-markdown-editor#119]
I've been trying various methods to get form submission when hitting the **ENTER** key, but it's not seems to work :

``` javascript
$('#message').keypress(function( event ) {
    alert( event.keyCode );
    if( event.keyCode == 13 ) # Never pass
      ...
});

$('.CodeMirror').keypress(function( event ) {
    alert( event.keyCode );
    if( event.keyCode == 13 ) # Never pass
      ...
});

editor.codemirror.on("keypress", function( instance, event ) {
    alert( event.keyCode );
    if( event.keyCode == 13 ) # Never pass
      ...
});
```

Events are not triggered when I press **ENTER** key but it's work when I hit letters/numbers.
Any help would be great.

**Comment by hardware** [comment]
Any ideas ? I would like to find a way to do this.

**Comment by WesCossick** [comment]
Sorry for the delayed response, I've been very busy lately. I'll need some time to take a closer look at this and do some testing. I'll report back when I've discovered the issue.

**Comment by WesCossick** [comment]
So the 'enter' key is being handled by SimpleMDE already, so what you need to do is this:

``` js
simplemde.codemirror.on("keyHandled", function(editor, event){
    if(event == "Enter") {
        console.log("Enter pressed");
    }
});
```

**Comment by hardware** [comment]
Nice, thank !
