### ISSUE TITLE
Multiple editors on the same page

### ISSUE THREAD

**Issue by lumenwrites** [sparksuite/simplemde-markdown-editor#12]
First of all - thank you for the incredible editor, it is amazing. I need this thing very much, and I'm sure a lot of people will too. This is an extremely valuable project.

I have noticed a bug, or maybe I'm just not using it right.

I have a nested commenting system on my website(like reddit). Each comment has a textarea for typing in the reply. I'm trying to render the editor in each of the areas.

```
$('textarea').each(function() {
        var simplemde = new SimpleMDE(this);
        simplemde.render(); 
 })
```

But it ends up rendering the 2nd editor right after the first one, not inside the correct text area.

Can you help me out with this?

**Comment by lumenwrites** [comment]
Oh, sorry, this worked:

```
$('textarea').each(function() {
    var simplemde = new SimpleMDE({
        element: this,
    });
    simplemde.render(); 
})
```

Oh, ma-an, this will make my website so much better =)

**Comment by WesCossick** [comment]
So glad to hear that SimpleMDE came in handy! And hopefully others will find this `.each()` trick useful as well.
