### ISSUE TITLE
Ordered Lists

### ISSUE THREAD

**Issue by aanchalgera** [sparksuite/simplemde-markdown-editor#120]
If I write some text like
Apple
Orange
Papaya

And select all of it and click Ordered list, the markdown is
1. Apple
1. Orange
1. Papaya

Instead of 
1. Apple
2. Orange
3. Papaya

**Comment by WesCossick** [comment]
Markdown processes any number followed by '. ' as an ordered list item. So while this may not be the most visually perfect way of creating an ordered list, it will not affect the final rendered HTML. Therefore this will probably not be something we fix right away, if ever.
