### ISSUE TITLE
Tab key behaviour

### ISSUE THREAD

**Issue by buzdyk** [sparksuite/simplemde-markdown-editor#122]
Hi,
If SimpleMDE is used in a form with many inputs some of users are very likely want to tab across the whole form. Current logic would make such user use mouth to focus out of the SimpleMDE textarea.

Is there any workaround to make "Tab" & "Shift-Tab" tab into another form input instead of indenting?

**Comment by WesCossick** [comment]
At this time I do not have plans of implementing this functionality for SimpleMDE. If you'd like, you can submit a PR with this functionality attached to an optional boolean option.

**Comment by fredericseiler** [comment]
``` js
var editor = new SimpleMDE();

editor.codemirror.options.extraKeys['Tab'] = false;
editor.codemirror.options.extraKeys['Shift-Tab'] = false;
```
