### ISSUE TITLE
How INSTALL?

### ISSUE THREAD

**Issue by Master-Antonio** [sparksuite/simplemde-markdown-editor#123]
Hello.
Sorry for this query.
But how install this?
I download the zip , only serve the folders SRC-DIST or also gulpfile.js ext ext?
Need something on Server-Side ( Nodejs ext ext ) ?
What files should I include in the page? ( Only simplemde.min.css and simplemde.min.js ) .

**Comment by WesCossick** [comment]
The two minified distributions files (one JS, one CSS) need to be included on the page before initializing SimpleMDE. See https://github.com/NextStepWebs/simplemde-markdown-editor#quick-start for more info.

**Comment by Master-Antonio** [comment]
And stop? Only js and css? Because in zip there are a lot of files, js and css.
Need something for server? Or work only including the 2 files in page?

**Comment by WesCossick** [comment]
Yes, only those two files. Please read the quick start guide.

**Comment by Master-Antonio** [comment]
I read the guide, but does not say anything about server side.

**Comment by danabrey** [comment]
You don't need to install anything on your server to use SimpleMDE. Including the two aforementioned files from a public directory is all you need to do. 

The rest of the files in the repository are for development and for 'building'  from the source I'm case you wish to do so.

**Comment by Master-Antonio** [comment]
Thanks.
But when i send, dont work.
The text is not formatted in HTML.
