### ISSUE TITLE
CSS Active on button multiple times

### ISSUE THREAD

**Issue by Psychokrameur** [sparksuite/simplemde-markdown-editor#128]
Hello,
After multiple click on a button, the css class "active" appear multiple times

``` html
<a title="Bold (⌘+B)" class="fa fa-bold active active"></a>
[...]
<a title="Quote (⌘+')" class="fa fa-quote-left active active active active active active active active"></a>
```

**Comment by WesCossick** [comment]
Can you set up a JSFiddle that replicates this with exact steps on how to reproduce the issue?

**Comment by Psychokrameur** [comment]
Just go on your demo website : http://nextstepwebs.github.io/simplemde-markdown-editor/
On your first example do:
- click on "bold" button
- click on "quote" button
- click on "bold" button  

You'll see the CSS of your "quote" button with 3 active

(Tested in Chrome and Safari)

PS: By the way, not a very important issue ;)

**Comment by WesCossick** [comment]
I see now. This really doesn't affect the functionality, so I don't plan on fixing this. Someone can submit a PR though if they're interested.
