### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by FabianKoestring** [sparksuite/simplemde-markdown-editor#129]
What about adding bower support?

**Comment by WesCossick** [comment]
I'll consider it, though I haven't used bower in the past. I'll look up some documentation on how to do it.

**Comment by WesCossick** [comment]
If @FabianKoestring or someone else with more experience with bower than me wants to submit a PR that accomplishes this, that would be very helpful as well.

**Comment by FabianKoestring** [comment]
@WesCossick  - Yea, i´ll try that.
