### ISSUE TITLE
At.js Support

### ISSUE THREAD

**Issue by jackperry** [sparksuite/simplemde-markdown-editor#13]
Not sure if this is a limitation on SimpleMDE's end or CodeMirror's end (since CodeMirror does all the editing in pre>span tags, but getting [At.js](https://github.com/ichord/At.js) to work is just too lofty a goal today it seems.

Any insight you can provide on how this might be possible?

**Comment by WesCossick** [comment]
Unfortunately I'm not familiar with At.js, but I would suspect it has to do with the way CodeMirror works. Specifically with the fact that CodeMirror does not edit the content of a `textarea`; rather, it uses the `pre>span` tags like you mentioned.

It would probably take quite a bit of manual effort to make At.js support CodeMirror. I would imagine that it would need a custom CodeMirror plugin to do the heavy-lifting.
