### ISSUE TITLE
Question: CodeMirror

### ISSUE THREAD

**Issue by Psychokrameur** [sparksuite/simplemde-markdown-editor#130]
Hello,

Simple question, does the codemirror.js file is the standard CodeMirror or this is a custom version made for SimpleMDE ?

Thanks
(eg. does we need to use this file if we already have an instance of CodeMirror imported elsewhere in our app)

**Comment by WesCossick** [comment]
The `codemirror.js` file is the standard CodeMirror JS file with no modifications. It's bundled into the final minified script (`simplemde.min.js`), so it cannot be separated at this point.
