### ISSUE TITLE
Question: preview

### ISSUE THREAD

**Issue by Psychokrameur** [sparksuite/simplemde-markdown-editor#131]
Hello,

How can know if the editor is in mode preview or not?
I did not see any attribute or methods `isPreview`

Tanks in advance

**Comment by WesCossick** [comment]
Currently there is no externally available function for users to check if SimpleMDE is in preview mode. Do you have a specific use for this? It may be a good idea to add something like this.

**Comment by Psychokrameur** [comment]
Yes I do :).
I'm using simplemde in a field which can be readOnly depending on the user access right. So when it's readOnly I want to put simplemde in preview mode. 
As this "readOnly mode" need to be dynamic, at some point I need to know the actual state of simplemde.

**Comment by WesCossick** [comment]
Sounds good, I've added it to the next milestone.

**Comment by WesCossick** [comment]
Added three new "state methods" in commit efc38f43dabf84345fa60811373473862d7a693d.
