### ISSUE TITLE
Preview overlap with side-by-side or fullscreen

### ISSUE THREAD

**Issue by Psychokrameur** [sparksuite/simplemde-markdown-editor#133]
Hello,

Go on your demo page : http://nextstepwebs.github.io/simplemde-markdown-editor
1. pass the first editor in mode preview
2. pass the second editor in mode full screen or side-by-side
You should see the first editor overlapping your second editor.

I think that the problem comes simply that you put the same `z-index` (999) for the different modes.
Put 998 on `.editor-preview` class and this should fix this.

**Comment by WesCossick** [comment]
Ah, good catch! We'll get that corrected for the next release.

**Comment by WesCossick** [comment]
Fixed with 03b5ed2551d297bf36a8806bfaf22d0e90218610
