### ISSUE TITLE
Option for using default CodeMirror HTML highlighting

### ISSUE THREAD

**Issue by danabrey** [sparksuite/simplemde-markdown-editor#135]
The project that we're using SimpleMDE for requires a fair amount of mixed HTML/Markdown editing (a slow changeover to using Markdown as the preferred syntax for user- and staff-generated content). I notice that in the initialisation of CodeMirror within SimpleMDE, the theme is set to "paper", a non-existent theme, so that the default CodeMirror CSS for styling opening/closing HTML tags and HTML errors is not included.

This is for obvious reasons, as SimpleMDE is for pure Markdown editing, but bearing in mind our use case and the probability of others having similar needs, would it be worth adding a simple boolean option for using the default CodeMirror styling if needed?

**Comment by WesCossick** [comment]
This is a possible idea, I'll look into the feasibility of such an option

**Comment by danabrey** [comment]
Okay, great. See https://github.com/danabrey/simplemde-markdown-editor/blob/master/src/js/simplemde.js#L910 for the solution that we're using at the moment.

**Comment by WesCossick** [comment]
So with the `default` theme, there's quite a bit of coloring for things that maybe don't need color.

<img width="618" alt="screen shot 2015-10-20 at 2 34 03 pm" src="https://cloud.githubusercontent.com/assets/3850064/10618837/c2dbe40a-7737-11e5-95c3-0610bd95aaa2.png">

I like the idea of adding color to HTML tags, so I believe it'd be best to integrate HTML tag coloring directly into SimpleMDE's stylesheet, no need for an option. As I see it, we only need to add color to the following classes: `cm-tag`, `cm-attribute`, `cm-string`.

Thoughts?

**Comment by danabrey** [comment]
Sounds great to me, much better than pulling in lots of colour that's unneccessary. I'll submit a pull request adding those, see what you think.

**Comment by mjau-mjau** [comment]
+1 that would be really sweet. No need for extensive coloring of html tags, just something to emphasize the tags and put them in context.
