### ISSUE TITLE
Include source?

### ISSUE THREAD

**Issue by fraserredmond** [sparksuite/simplemde-markdown-editor#14]
Hi, just spent a couple of hours looking at and comparing markdown editors, and SimpleMDE/lepture seems like the best.

Great to see that you're continuing to add to the project and keep it alive :-)

One concern I have with committing to SimpleMDE is that if you get busy with other things, the code isn't public to fork or submit pull-requests against. Do you have any plans to include the source in the repo?

A few of the features I'd be interested in, and would consider adding pull-requests for:
- More toolbar buttons (h1, h2, h3, hr, etc)
- tooltips (html title attribute) on the toolbar buttons

**Comment by WesCossick** [comment]
Glad to hear that you enjoy it! All of the source files are included in the folder [/source files/](https://github.com/NextStepWebs/simplemde-markdown-editor/tree/master/source%20files). You should be able to fork the repo and create pull requests against this code.

I've considered extra/customizing toolbar buttons along with tooltips. I've created issues #16 and #17 to keep track of these ideas.

**Comment by fraserredmond** [comment]
Oh, sorry, I don't know how I missed simplemde.js there! :blush:
