### ISSUE TITLE
Destroying SimpleMDE instance

### ISSUE THREAD

**Issue by JulienTant** [sparksuite/simplemde-markdown-editor#142]
Hello,

I would like to know what's the best way to destroy an instance of SimpleMDE ?

**Comment by WesCossick** [comment]
Right now there isn't a way to destroy SimpleMDE. But this may be a good candidate for future functionality.

**Comment by JulienTant** [comment]
because SimpleMDE don't create "wrapper" arround his blocks, this is my "hacky" solution right now :

``` javascript
// myTextareaElement is a variable containing my textarea element
var parent = myTextAreaElement.parentElement;
var simpleMdeClasses = ['editor-toolbar', 'CodeMirror', 'editor-preview-side' ,'editor-statusbar'];
for (var i in simpleMdeClasses) {
    var elementToRemove = parent.querySelector('.' + simpleMdeClasses[i])
    elementToRemove && elementToRemove.remove();
}
myTextAreaElement.style.display = "";
```

If we could have a `<div class="simplemde-container" />` or something, it would have been simpler :)

**Comment by jure** [comment]
Yes, this is very much needed in a bigger app. Instances stick around when navigating pages within a React application, for example.

**Comment by alekkowalczyk** [comment]
I can't use it because of lack of this functionality, great library, but without the destroy functionality not usable in more complex scenarios.

**Comment by trwired** [comment]
This is something I also have a problem with. A workaround is, of course, possible, but it also muddles my app's code. Does the issue's status as something set for v2.0 milestone mean you wouldn't currently accept a PR solving it?

**Comment by WesCossick** [comment]
@trwired no, it does not mean that. That's just an indication of when I plan to complete it barring no PR is submitted for it.
