### ISSUE TITLE
Including mustache overlays

### ISSUE THREAD

**Issue by samuelcolvin** [sparksuite/simplemde-markdown-editor#144]
Hi this looks really cool, I've been hunting for a simple but decent markdown editor for ages.

At tutorcruncher we currently use a codemirror editor with a modified mustache overlay at bit like [this](https://codemirror.net/demo/mustache.html). (The only difference is we've extended it so variables are horrible and black if they don't exist.)

How would we more easily integrate this overlay with _simplemde-markdown-editor_? Do we have to fork the project and modify or is there any chance of way to use the overlay with the distributed version?

**Comment by WesCossick** [comment]
Glad you like it! You'd need to fork the repo and make the necessary modifications to get the mustache overlay working, this isn't something I plan to add to SimpleMDE's core functionality.

**Comment by samuelcolvin** [comment]
great, thanks for the reply.
