### ISSUE TITLE
If I use my own toolbar, the actions aren't working anymore

### ISSUE THREAD

**Issue by kaju74** [sparksuite/simplemde-markdown-editor#147]
If I define a toolbar item like this:

```
        toolbar: [
            {
                name: 'bold',
                action: toggleBold,
                className: 'fa fa-bold',
                title: 'Fett (Ctrl+B)'
            } ...
```

I got an js-error, that "toggleBold" is not defined.

Regards,
Marc

**Comment by WesCossick** [comment]
Probably due to the change to UMD design. I'll look into it.

**Comment by kaju74** [comment]
Thank you...

**Comment by Vercoutere** [comment]
Yep, just bumped into the same issue.

**Comment by WesCossick** [comment]
You'll need to use `action: SimpleMDE.toggleBold,` from now own when creating a custom toolbar. I've updated the README in the development branch to mention this, which will go out with the next release.
