### ISSUE TITLE
Hidden toolbar actions are callable throught it's shortcut

### ISSUE THREAD

**Issue by kaju74** [sparksuite/simplemde-markdown-editor#148]
Let's say, I've disabled the fullscreen feature...this action can still be called if I click the (default) assigned shortcut, even if this action is not part of my own toolbar settings or has been removed through "hiddenFields".

**Comment by WesCossick** [comment]
The toolbar is separate from the shortcuts, but it might not be a bad idea to create an option for shortcuts.

**Comment by WesCossick** [comment]
I won't be adding an option to disable shortcuts because they can individually be disabled as of PR https://github.com/NextStepWebs/simplemde-markdown-editor/pull/223

Most people still want shortcuts to work any way even if the toolbar is hidden.
