### ISSUE TITLE
Boolean option to forget autosave on submit + function to forget saved text

### ISSUE THREAD

**Issue by wstoettinger** [sparksuite/simplemde-markdown-editor#153]
Why is it necessary to set a unique_id to use autosave? (i get the message "SimpleMDE: You must set a unique_id to use the autosave feature"). Why doesn't it just save to the textarea element with which it's initialized as a default?

**Comment by wstoettinger** [comment]
found a solution listening to the blur event of codemirror 

```
simplemde.codemirror.on("blur", function() {
    $(self).text(simplemde.value()); // self is the textarea dom element
});
```

this would be the expected behavior in my opinion.

**Comment by WesCossick** [comment]
The `unique_id` is used when saving the data to the browser. It's used to distinguish one editor from another on a website that has multiple instances of SimpleMDE.

**Comment by wstoettinger** [comment]
i'm still trying to figure out what that exactly is. it saves data "to the browser", does that mean it sort of set's a cookie to continue editing where someone let off after reopening the browser? if yes, then i somehow misinterpreted the documentation.

**Comment by WesCossick** [comment]
Autosave saves the data to local storage, rather than a cookie, but yes, a user can continue where they left off if they close the tab or accidentally leave the page. I'll work on making the documentation more clear.

**Comment by wstoettinger** [comment]
i understand. 

curiously, i had to turn it off again because it didn't load the initial text from the textarea anymore after a form submit. I my use case, I have to edit text which is stored on the server, the user presses submit to save it, after he clicks on edit again, the simplemde was empty, despite the (hidden) textarea containing the right content. is this a bug or am i doing something wrong?

after the submit, the editor stays empty rather than loading the text from the textarea on which it was initialized. I even tried  the "value" function without success until i turned off the autosave again.

**Comment by WesCossick** [comment]
I'll look into the problem with the value function, but the editor is designed to forget the autosaved text on a form submit. The thinking is that once it's submitted, it doesn't need to be saved anymore since now it's in the hands of the server. Might add a boolean option to modify this behavior.

_Note to self: create method to forget autosaved text_

**Comment by wstoettinger** [comment]
yes, i figured that this is the intended behavior, but after it "forgets" the value, it should load the textarea value again, like at the first time, shouldn't it? futhermore, what happens if the value is changed by somebody else in the meantime? conflicting overwrites will be inevitable. i'm getting to doubt that this feature is very useful in a multi-user environment.

PS: great and timely responses here! keep it up :)

**Comment by WesCossick** [comment]
Autosaving just saves the content to the user's browser, so it's not possible to have conflicts with other users. Your own system may experience this if it does some form of syncing on the backend, but this would not be an issue addressed by SimpleMDE.

**Comment by wstoettinger** [comment]
ok, let me explain: User A loads data in a form, does some editing and decides not to submit it. User B opens the same form, does some editing and submits it. Then User A opens the browser again and continues, then submits. All changes from User B are lost, right?

**Comment by WesCossick** [comment]
SimpleMDE is just a frontend Markdown editor, your own application logic would need to address this problem.

**Comment by 19peaches** [comment]
No this is your preview renderer this isn't working correctly. **Not** your fault, because the problem lies in the marked repo, but maybe a fork of marked with a fix would be in order. You're using your own fork of spell-check so might as well fork marked and fix the issue so your highlight feature will work no?

**Comment by wstoettinger** [comment]
that's absolutely true! and it's definitely a very awesome editor! 

i just wanted to point out this problem, which makes the autosave feature not usable in our case, to other people as well, so they use this feature wisely.

**Comment by wstoettinger** [comment]
just created a pull request to update the readme with a small how-to for this situation.
