### ISSUE TITLE
hljs Class Not Added to Highlight Span

### ISSUE THREAD

**Issue by ghost** [sparksuite/simplemde-markdown-editor#158]
When attempting to use the code highlighting, the `.hljs` class is not getting added to the span that wraps the code. The elements within the span all have the `hljs` prefix, so they are being colored, but the span itself only has the language class in it.

Screen:

![screen shot 2015-11-04 at 8 20 28 am](https://cloud.githubusercontent.com/assets/1456472/10946238/695844a2-82de-11e5-9ad2-ee4cf12199be.png)

This block should look like so:

``` html
<pre>
    <code class="lang-php">
        <span class="php hljs">
            <span class="hljs-preprocessor">...</span>
            <span class="hljs-comment">...</span>
            <span class="hljs-keyword">...</span>
            <span class="hljs-title">...</span>;
        </span>
    </code>
</pre>
```

Is this an issue with SimpleMDE or Highlight.js?

Thanks

**Comment by WesCossick** [comment]
Sounds like this is an issue with highlight.js. SimpleMDE doesn't handle this component of the DOM manipulation.

**Comment by ghost** [comment]
Actually it turns out it's an issue in Marked. The code block is where the `hljs` class should be implemented, not in the span as I posted earlier. 

That repo is rarely ever updated so I don't imagine it's going to get fixed.

Thanks.

**Comment by Offerel** [comment]
how do you have fixed this?

**Comment by yaozhibo** [comment]
Hey man, how do you have fixed this? I'm confusing with this for a long time!!!
