### ISSUE TITLE
`spellChecker: true` causes an error in IE9

### ISSUE THREAD

**Issue by ellerynz** [sparksuite/simplemde-markdown-editor#159]
Hi there,

Trying out the demo page in IE9 and the editors aren't working as expected. Checking the console, there's the following error:

```
SCRIPT5: Access is denied
line 96 character 2
```

I get the same error in my project when testing in IE9.

For the demo, line 96 is the third editor being created. It is created without the `spellChecker` option (i.e. `spellChecker: true`). Setting `spellChecker: false` gets everything to work as expected.

Haven't looked into it more than that. Could be a CodeMirror issue rather than SimpleMDE one, or perhaps the demo and my project are missing something.

**Comment by WesCossick** [comment]
Unfortunately I do not have access to IE9 to do testing with it. In general, older IE browsers (especially 4+ years old) will not be explicitly supported by SimpleMDE. If you'd like to identify the issue and submit a PR, you can do so.

**Comment by ellerynz** [comment]
Yea, I completely understand — was mostly pointing out in case anyone else needed a workaround :smile:
