### ISSUE TITLE
Markdown Guide Button is focusable in tab order

### ISSUE THREAD

**Issue by wstoettinger** [sparksuite/simplemde-markdown-editor#163]
I'm using the SimpleMDE in a form and when tabbing through the form input elements the Markdown Guide button is focused before the editor gets the focus. 

I could fix this by setting tabindex="-1" on the <a>. I have no idea why it is focusable in the first place, I'm using the latest version of chrome, maybe it's browser specific.

**Comment by WesCossick** [comment]
I'll correct it for the next release
