### ISSUE TITLE
scrollbar not working for preview in fullscreen mode

### ISSUE THREAD

**Issue by KrishnaPG** [sparksuite/simplemde-markdown-editor#166]
The behavior is reproducible with both CDN version and demo:
-   write long content and go to fullscreen
-   click on 'preview' button (so that only preview is visible)
-   try scrolling using the scroll bar - nothing happens

**Comment by WesCossick** [comment]
Looks like it's because `CodeMirror-vscrollbar` has a `z-index` of `6`, which is higher than the preview area's.
