### ISSUE TITLE
How to control the Preview style / theme?

### ISSUE THREAD

**Issue by KrishnaPG** [sparksuite/simplemde-markdown-editor#168]
The generated html (from markdown) is separate entity from the original page (that is holding the editor).

Right now, the generated preview is inheriting the styles from the "editor-container-page", for the lack of better word. But if the preview need to be viewed with a different style (css link), would this support such a scenario?

**Comment by KrishnaPG** [comment]
Here is one example http://vuejs.org/examples/ where they are achieving preview styling and also non-full-screen side-by-side previews. Perhaps its implementation can give some pointers.

**Comment by WesCossick** [comment]
You'd need to apply styling to the preview dividers yourself.
