### ISSUE TITLE
Shortcuts turning off

### ISSUE THREAD

**Issue by davede-git** [sparksuite/simplemde-markdown-editor#169]
Hi,

I need to know how to turn off all of shortcuts. When I press L + ALT it gives me ordered list. My language is polish so I need " ł " character insteed of list.

**Comment by WesCossick** [comment]
Right now the shortcuts cannot be disabled. I'll consider this for future development though.

**Comment by davede-git** [comment]
Are there no alternative ways? I really like this editor but I can't work properly beccause of shortcuts.

Thanks for your reply.

**Comment by WesCossick** [comment]
You can fork the repo and disable the shortcuts yourself. Or if you really want to be helpful, you can submit a PR that includes a new option to disable the shortcuts. That's the best way to expedite this feature.

**Comment by WesCossick** [comment]
Fixed in https://github.com/NextStepWebs/simplemde-markdown-editor/pull/223
