### ISSUE TITLE
Markdown writing desktop app

### ISSUE THREAD

**Issue by maccadia** [sparksuite/simplemde-markdown-editor#171]
Hi,

I'm writing tech docs and I'm desperately searching for some kind of WYSIWYG markdown editor to use in my [git + markdown + pandoc + latex] workflow. Actually, I have some design ideas for making a writing app but I'm lacking Web tech / JS proficiency (I'm so disappointed, I should do something about that !).

How difficult would it be to make a basic desktop app with SimpleMDE ? Maybe with [Electron](http://electron.atom.io/) ?
I think I just have to find how to implement `open from disk` and `save to disk`? (By the way, I saw that there is an autosave feature but where is it saved ?)

Best,

M.A.

**Comment by WesCossick** [comment]
I'm not very familiar with Electron so I wouldn't be able to tell you. Sorry.

The autosave data is saved to the browser's local storage.
