### ISSUE TITLE
Why not using browser spell-ckecking ?

### ISSUE THREAD

**Issue by maccadia** [sparksuite/simplemde-markdown-editor#172]
I don't know how spell checking is implemented in SimpleMDE but I wonder why not using browser spell-checking capabilities. It would get multi-language support for free.

[Calmly](http://www.calmlywriter.com/online/) does that.

Best,

M.A.

**Comment by WesCossick** [comment]
Due to the way SimpleMDE functions, it is not possible to use the browser's spell checking.

**Comment by maccadia** [comment]
I managed to get misspelled words underlined by adding the attribute `contenteditable="true"` but no correct spelling appears on right click. This might be due to the way SimpleMDE functions.

Anyway, thanks for your answer.
