### ISSUE TITLE
Uncaught ReferenceError: CodeMirror is not defined

### ISSUE THREAD

**Issue by shinygang** [sparksuite/simplemde-markdown-editor#175]
`Uncaught ReferenceError: CodeMirror is not defined` in spell-checker.js file at line 10.

**Comment by WesCossick** [comment]
You'll need to provide code examples of how you're using SimpleMDE. Maybe even setup a JSFiddle that reproduces the error.

**Comment by shinygang** [comment]
@WesCossick 
first,I use 'npm install --save-dev simplemde',
second,I use 'require("simplemde")' in my XXX.vue，and there has error:

```
Uncaught ReferenceError: CodeMirror is not defined in spell-checker.js file at line 10.
```

I see the spell-checker.js's code,there has not define the 'CodeMirror' and not reuqire 'CodeMirror'.

**Comment by WesCossick** [comment]
I'm not very familiar with module loading as I don't use it in my workflow. Someone else may need to help answer this.

**Comment by rscnt** [comment]
@shinygang, @WesCossick This was already fixed by [@universome](https://github.com/universome/codemirror-spell-checker) :smile: 

See NextStepWebs/codemirror-spell-checker#14

**Comment by WebCloud** [comment]
we now have a pull request for this: https://github.com/NextStepWebs/codemirror-spell-checker/pull/18
