### ISSUE TITLE
How to send data using post form with php?

### ISSUE THREAD

**Issue by abr4xas** [sparksuite/simplemde-markdown-editor#176]
Hi there, 

How to send data using post form with php?

![captura de pantalla 2015-11-13 a la s 21 23 22](https://cloud.githubusercontent.com/assets/405484/11161375/30a12676-8a4d-11e5-8b08-b8931231ee8a.png)

Doesn't work :disappointed: 

But, using preview mode works

![captura de pantalla 2015-11-13 a la s 21 27 46](https://cloud.githubusercontent.com/assets/405484/11161389/6ccd3e6e-8a4d-11e5-8bcd-b623b6b95ad1.png)

**Comment by WesCossick** [comment]
Can you post relevant HTML and PHP code? Hard to debug without that.

**Comment by abr4xas** [comment]
Hi, 

This is my form

``` html
<form role="form" method="post" action="test.php" name="myForm" id="myForm">
     <textarea class="form-control" rows="3" id="my-post" name="post"></textarea>
     <button class="btn btn-default" type="submit">Send</button>
</form>
```

``` js
<script>
var simplemde = new SimpleMDE({ 
    element: document.getElementById("my-post") 
});
</script>
```

Php code, only this:

``` php
print_r($_POST);
```

**Comment by WesCossick** [comment]
I believe this may be something on your end. I am unable to reproduce this error using the code snippets you provided.

Here's the full file I used: **test.php**

``` PHP
<?php
print_r($_POST);
?>

<form role="form" method="post" action="test.php" name="myForm" id="myForm">
     <textarea class="form-control" rows="3" id="my-post" name="post"></textarea>
     <button class="btn btn-default" type="submit">Send</button>
</form>

<link rel="stylesheet" href="//cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
<script src="//cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>

<script>
var simplemde = new SimpleMDE({
    element: document.getElementById("my-post")
});
</script>
```
