### ISSUE TITLE
Full-screen edit mode

### ISSUE THREAD

**Issue by fraserredmond** [sparksuite/simplemde-markdown-editor#18]
Just demo'ed SME to a colleague, and they had a suggestion:

Toolbar button to resize the editor to the full size of the window.

(Github textarea's have it, if you want an idea of how it looks.)

**Comment by yaffol** [comment]
This would be a great feature - I use codemirror in full-screen mode quite often, and it's very useful. 
http://codemirror.net/demo/fullscreen.html

**Comment by WesCossick** [comment]
Added fullscreen support in [this commit](https://github.com/NextStepWebs/simplemde-markdown-editor/commit/fc6fd130255956f936cbd51452b5edd74c4c3a37)
