### ISSUE TITLE
Consider to support the image and file upload

### ISSUE THREAD

**Issue by ElderJames** [sparksuite/simplemde-markdown-editor#190]
Hi!
This is a very wonderful project,but I think it can be more powerful.
I think it can be added the file upload function and the file path from server would be inserted into the editer shortcut.

**Comment by WesCossick** [comment]
This is likely not a feature that will be added to SimpleMDE because it focuses just on the front end right now.

**Comment by cnjiangjun** [comment]
Hi,
Yes, it needs some extra code requesting to server.
But I think at least you can add a method to support customizing editing the image url before inserting it to editor filed instead using window.prompt.

For example, I add a dialog when clicking 'fa-image', in this dialog I add a textarea which user can upload file via ajax and get back the url of this file and insert it to the textarea. After that if I click OK button in the dialog, I call the SimpleMDE.drawImage method, but I must overwrite window.prompt to return the value of textarea. 

Do you think it's good feature that you will suppot?

Thanks.

**Comment by ElderJames** [comment]
Thanks for your suggestion！That's actually a good feature.
And I wonder if the use sense likes the editor on Ghost blog system.On that markdown editor,when I type a image shortcut,it will present a upload area on the explore side,which allows me to click it to choice a picture to upload.

**Comment by WesCossick** [comment]
Duplicate #328
