### ISSUE TITLE
Placeholder?

### ISSUE THREAD

**Issue by symsmith** [sparksuite/simplemde-markdown-editor#191]
Hello is it possible to add a placeholder?
Thanks

**Comment by samdark** [comment]
It's possible in CodeMirror: https://codemirror.net/demo/placeholder.html

**Comment by WesCossick** [comment]
I'll look into the possibility of incorporating this into SimpleMDE.

**Comment by symsmith** [comment]
Ok cool

**Comment by Master-Antonio** [comment]
Yes . It would be very useful .
simplemde.placeholder ( " message " ) ;
Do in this way.

**Comment by adam187** [comment]
@WesCossick here is PR with placeholder option https://github.com/NextStepWebs/simplemde-markdown-editor/pull/198

**Comment by symsmith** [comment]
Thanks!

**Comment by WesCossick** [comment]
Added in PR #199.

**Comment by ghost** [comment]
When will placeholders be supported? :)

**Comment by WesCossick** [comment]
Placeholders are currently supported on the development branch, and will be released on the stable master branch with the next version of SimpleMDE.

**Comment by ghost** [comment]
very nice - looking forward :+1:
