### ISSUE TITLE
Have SimpleMDE keep the <textarea> updated with new content

### ISSUE THREAD

**Issue by dbkaplun** [sparksuite/simplemde-markdown-editor#193]
Would be great if it was! Also would be nice if SimpleMDE could listen for changes in the textarea.

**Comment by WesCossick** [comment]
It's an idea. Though there should be many easy workarounds to this, including writing a small script using the built-in listeners.

**Comment by jaydave** [comment]
this is easily doable by putting below code in `render` where `this.codemirror` is defined

```
var cm = this.codemirror;
  cm.on("update", function() {
    el.innerHTML = cm.getValue();
  });
```

Do we want to provide this as configurable option ?

**Comment by WesCossick** [comment]
This could be a configurable option, yes. If you're interested, I wouldn't mind a PR that accomplished this.

**Comment by jbanety** [comment]
:+1:
