### ISSUE TITLE
events (eg keypress)

### ISSUE THREAD

**Issue by fraserredmond** [sparksuite/simplemde-markdown-editor#20]
How do you catch a keypress event on simplemde? is it something to do with:

```
simplemde_letterBodyEdited.codemirror.on()
```

Or something to do with this? https://codemirror.net/doc/manual.html#events

**Comment by fraserredmond** [comment]
Setting a event handler on the form works (as a fallback option.)

**Comment by WesCossick** [comment]
```
var simplemde = new SimpleMDE();
simplemde.codemirror.on("keyHandled", function(){
    console.log(simplemde.value());
});
```
