### ISSUE TITLE
Support right-to-left languages

### ISSUE THREAD

**Issue by ali-zohrevand** [sparksuite/simplemde-markdown-editor#200]
hi..
this project is cool and i want use it. but it does not support rtl language. could you pleas consider adding this  feature?
thanks a lot

**Comment by WesCossick** [comment]
I'm not opposed to the idea, but someone more familiar with right-to-left languages would need to submit a PR for this. I am not completely aware of what changes would need to be made.

**Comment by ali-zohrevand** [comment]
this [project](https://github.com/hasenj/showdown) support rtl but has poor ui... 
it is very simple in html. just need a css code that make text-align=right and direction=rtl
.... 
thank for considering it as idea

**Comment by WesCossick** [comment]
I see. I've added this feature to the next milestone.

**Comment by ali-zohrevand** [comment]
thanks again 
it would be wonderful

**Comment by WesCossick** [comment]
Unfortunately, CodeMirror (the underlying project that powers SimpleMDE) does not support RTL languages. The developer doesn't have the time, but could possibly get it done if he was sponsored by a company to do so. Until CodeMirror supports RTL, SimpleMDE will not.

For reference: https://github.com/codemirror/CodeMirror/pull/3190

**Comment by Flimm** [comment]
CodeMirror does now support bi-directional text:

https://codemirror.net/demo/bidi.html

**Comment by WesCossick** [comment]
Seems like this feature is old, not something that was released after the CodeMirror issue mentioned earlier.

**Comment by MajidCS** [comment]
This [Project](https://github.com/dariubs/rtlmd)  support  right-to-left languages

**Comment by MajidCS** [comment]
@WesCossick  Can use this [Support RTL : CodeMirror](https://rawgit.com/cben/CodeMirror/37a71a50360a7379e3b1ac55768b96ae8c357feb/demo/bidi.html)

**Comment by MajidCS** [comment]
@WesCossick Please look on this 

[https://github.com/kazzkiq/CodeFlask.js/pull/28](https://github.com/kazzkiq/CodeFlask.js/pull/28)

[https://github.com/kazzkiq/CodeFlask.js](https://github.com/kazzkiq/CodeFlask.js)

CodeFlask is awesome micro code-editor

**Comment by senaps** [comment]
okay, i have this project, i have turned off the spell checker and am using it for Persian(rtl) without problem. the only problem that i have now, is setting the dir=rtl for the text area! so that i can write right to left.
i set it, disable the simplemde, i have rtl and it is perfect. i enable simplemde, i losse the writing rtl, but still can paste the text and apply the styles (Header, bold etc.) to it.

is there a way to release the lock! on dir tag for the textarea?

**Comment by JalalSordo** [comment]
Does SimpleMDE have support for rtl languages ?

**Comment by senaps** [comment]
@JalalSordo it doesn't. you should hack around it. the way i do it no is not using simplemd! i just use a normal rich text editor, and parse it's data into md.

**Comment by JalalSordo** [comment]
@senaps What do you suggest ? something like ckeditor ?

**Comment by senaps** [comment]
@JalalSordo  what i did was completely move to `ckeditor`, save the text in the db as normal, but whenever i need to show it as `markdown`, i use a simple python package(tomd) to convert the html to markdown. it's easy, fast and always gives nice usable result.
