### ISSUE TITLE
Custom markdown support in editing mode.

### ISSUE THREAD

**Issue by alekkowalczyk** [sparksuite/simplemde-markdown-editor#201]
In my use case, I would love to implement two behaviours:
- When the user types a #hashtag it gets highlighted in the editor (a word without a space after hash so that it differentiates from header)
- When the user starts typing a hashtag a typeahead suggestion appears.

Is it possible to implement this behavior in the v.1.9.0 of SimpleMDE?

**Comment by WesCossick** [comment]
Not out of the box, no. But if you created a CodeMirror plugin, then forked this repository and modified SimpleMDE to load that plugin, I bet you could achieve this functionality.

**Comment by alekkowalczyk** [comment]
Ok, thanks for showing me the direction.
Greets!
