### ISSUE TITLE
Undo button in toolbar?

### ISSUE THREAD

**Issue by jesseleite** [sparksuite/simplemde-markdown-editor#203]
What you think of providing undo / redo button options for toolbar?  I personally just CMD-Z, but a client asked about adding the button and I thought I'd throw the suggestions here.

PS. Loving simplemde! Thank you once again for your work on this man!

**Comment by Netzweberei** [comment]
:+1:

**Comment by JamieWohletz** [comment]
I've just made a [PR](https://github.com/NextStepWebs/simplemde-markdown-editor/pull/218) that adds this. Here's to hoping it gets merged!

**Comment by isab** [comment]
Does this Undo/Redo button still exist? I don't see anything about it in the Readme.
