### ISSUE TITLE
Selecting multiple lines and converting to ordered list results in only 1's

### ISSUE THREAD

**Issue by 7upcat** [sparksuite/simplemde-markdown-editor#212]
When select multi lines will add  '1. ' for each line e.g:

```
1. number1
1. number2
1. number3
```

Seems  stat's type always be null .

``` javascript
function getState(cm, pos) {
    pos = pos || cm.getCursor("start");
    var stat = cm.getTokenAt(pos);
    if(!stat.type) return {};
```

**Comment by WesCossick** [comment]
I'm not sure if I understand the problem, or how to recreate it. Could you elaborate a bit?

**Comment by 7upcat** [comment]
![p1](https://cloud.githubusercontent.com/assets/16057335/11947123/94ef09ea-a89d-11e5-8f2d-1cad741cf4a2.png)
![2](https://cloud.githubusercontent.com/assets/16057335/11947124/95eaf19c-a89d-11e5-8f8f-74fa136f8a62.png)

**Comment by 7upcat** [comment]
It should be:
1. ordered list1
2. ordered list1
3. ordered list1

**Comment by WesCossick** [comment]
This may be fixed in the future, but it'd be purely aesthetic. Markdown will convert any number followed by a period to an ordered list item.
