### ISSUE TITLE
I can't take the value with Jquery Serialize.

### ISSUE THREAD

**Issue by Master-Antonio** [sparksuite/simplemde-markdown-editor#219]
With jquery serialize dont work.
var dati = $("#form").serialize();

Form : textarea id="messaggio" name="testo"></textarea

Script to load the markdown : 
script
            var simplemde = new SimpleMDE({ element: $("#messaggio")[0] });
/script

**Comment by WesCossick** [comment]
Before you call `.serialize()`, you'll probably want to transfer the value of SimpleMDE back into the textarea. But you may want to check StackOverflow for more help with this problem.

**Comment by Master-Antonio** [comment]
Resolved in this way.
var dati = $("#form").serialize()+"&text="+simplemde.value();
