### ISSUE TITLE
Inconsistent style button states - Headings

### ISSUE THREAD

**Issue by paulsputer** [sparksuite/simplemde-markdown-editor#227]
Hi @WesCossick great work on SimpleMDE, I'm currently integrating into Gitblit (https://github.com/gitblit/gitblit).

I noticed that while the italic, bold, strikethrough, quote etc style buttons change to an active state when text of that style is selected the heading buttons don't appear to respond in the same way.

Would you accept a PR to fix this?

**Comment by adam187** [comment]
@paulsputer @WesCossick 

I'm currently working on this situation. PR should be ready this week.

A.

**Comment by paulsputer** [comment]
Fantastic, thanks @adam187

**Comment by WesCossick** [comment]
Thanks for catching this, and thanks @adam187 for working on a PR.

**Comment by adam187** [comment]
@paulsputer @WesCossick PR for this is ready https://github.com/NextStepWebs/simplemde-markdown-editor/pull/229
