### ISSUE TITLE
Hide markdown formatting characters

### ISSUE THREAD

**Issue by Radiergummi** [sparksuite/simplemde-markdown-editor#232]
Is it possible to hide the formatting characters, eg. asterisks around italic text? What I would like to end up with would be an editor where users have no idea they use markdown at all...

**Comment by adam187** [comment]
@Radiergummi then you should rather use some regular wysiwyg editor and covert html to markdown via https://github.com/domchristie/to-markdown or https://github.com/jonschlinkert/remarked

**Comment by WesCossick** [comment]
Agreed, there really isn't a great way of achieving this at the moment (I did attempt to hide all the markup, but it caused CodeMirror to behave oddly when selecting text and such.)
