### ISSUE TITLE
Add version

### ISSUE THREAD

**Issue by Psychokrameur** [sparksuite/simplemde-markdown-editor#234]
Hello,

For better tracking and info, I suggest to put the version of SimpleMDE in the code.

```
SimpleMDE.version = "1.9.0" 
```

or at least a comment at the beginning of your main file.

Thanks

**Comment by WesCossick** [comment]
The distribution and debug files all have the version:

```
/**
 * simplemde v1.9.0
 * Copyright Next Step Webs, Inc.
 * @link https://github.com/NextStepWebs/simplemde-markdown-editor
 * @license MIT
 */
```
