### ISSUE TITLE
Internationalization issues

### ISSUE THREAD

**Issue by ddrury** [sparksuite/simplemde-markdown-editor#244]
I'm integrating simplemde into a project that has strong support for a wide range of languages including those that display right-to-left and I have a few issues with it.
1. Translating the text in simplemde could be easier - the text for the toolbar tooltips can be internationalized by more of less duplicating the core code - eg

```
                    toolbar: [ 
                        {
                            name: 'bold',
                            action: SimpleMDE.toggleBold,
                            className: 'fa fa-bold',
                            title: '" . I18N::translate('Bold') . "',
                        },
```

would it be possible to have something like a config variable as an object containing all the translatable strings - something like

```
text: {
    bold:  '" . I18N::translate('Bold') . "',
    italic:  etc
}
```

2.The text for the status line is more problematic - putting it in the css pseudo ::before element makes it impossible to change - currently I have to create some new css classes on the fly and use jQuery.toggleclass to switch to these new classes.
3. Some of the css classes need a right-to-left rule for example:

```
dir=['rtl'] .CodeMirror-scroll{
    margin-left:-30px;
    margin-right:0;
}
```

BTW for version 1.10.0 the css in /src/css/simplemde.css isn't the same as that in /dist/simplemde.min.cs

**Comment by WesCossick** [comment]
If you'd like, you can submit a PR that accomplishes these requests in an intuitive way. RTL support will not be possible yet though (see #200).

**Comment by ddrury** [comment]
I didn't see issue #200 - apologies.
I'll need a while studying the simplemde internals before I attempt any PR but I'll give it a go.

**Comment by WesCossick** [comment]
Okay, in the meantime, I'll be closing this issue.
