### ISSUE TITLE
Keyboard shortcuts for custom buttons

### ISSUE THREAD

**Issue by justinvoelker** [sparksuite/simplemde-markdown-editor#248]
I am working to replace the behavior of the image button by creating a custom button to call my function.  However, it does not look like I can re-assign the Ctrl+Alt+I keyboard shortcut (assigned to drawImage action by default) to my new custom button.  The following code is not working but perhaps the ability to assign keyboard shortcuts to custom buttons does not yet exist (if not, can it be added?).

```
shortcuts: {
    "drawImage": null,
    "drawImageCustom": "Ctrl-Alt-I",  // This is the name of my custom function
},
```

**Comment by WesCossick** [comment]
This will need to be fixed in the next release

**Comment by WesCossick** [comment]
See #252 for progress on this.
