### ISSUE TITLE
Autocorrection on German language

### ISSUE THREAD

**Issue by ghost** [sparksuite/simplemde-markdown-editor#253]
Hello,

I have used simplemde on one of my projects, and now our client is facing editor issue. Here he describe:

> When he works on his tablet with bluetooth keyboard he gets suggested words from his device and the editor shows red highlighted words. when he tries to skip these suggestions (e. g. by hitting space) he gets forwarded / fall back to dashboard. So it seems to be a problem with the editor itself which reacts not correctly on typed commands.

Autocorrection is set to off. He is using Samsung Tablet, default android browser.

**Comment by WesCossick** [comment]
I'm going to need more details and step-by-step instructions on how to reproduce this problem. At the moment the issue is a little unclear.

**Comment by ghost** [comment]
It happens only on mobile devices (Samsung Galaxy Tab S2, android 5.0, default browser). It works fine with English texts, but after typing german words, it marks them red and I am not able to save it.

**Comment by WesCossick** [comment]
The dictionary is an English dictionary, so that's why it's marking German words as misspelled. You'll need to setup a JSFiddle for other issues though, so that they can be reproduced and fixed.

**Comment by alfonsrv** [comment]
There's a PR adding german and other languages, unfortunately wasn't approved in the last 7 years though: https://github.com/sparksuite/codemirror-spell-checker/pull/39
