### ISSUE TITLE
Handle rich-text copy-paste

### ISSUE THREAD

**Issue by kristianlm** [sparksuite/simplemde-markdown-editor#257]
This editor is one of the best I've found at not making my documents end up messy (with multiple italics and bold, for example) - really nice work! Here's my feature request:

Current scenario:
1. Write a document with SimpleMDE
2. Preview it
3. Copy the preview content into your clipboard
4. Start a new document with SimpleMDE
5. Paste the content back in

Actual: Pasted content has no formatting and all markup is lost
My wish: Pasted content contains the formatting
- Suggestion 1: When copying preview, copy the actual markdown content
- Suggestion 2: When pasting, capture pasted rich-text and convert to markdown (better, because that way you could copy-paste from google docs and friends too)

From [news.ycombinator](https://news.ycombinator.com/item?id=10446865):

> For example to handle paste, I've found the best way is to detect a paste, shift focus to another invisible contenteditable div, interpret the pasted content, and insert that into the actual editor through the editor's API. That way no weird/unexpected markup ends up in the editor (whether or not the editor also utilizes contenteditable).

**Comment by WesCossick** [comment]
This is a bit of an edge-case scenario and I don't think it's the best route to take for SimpeMDE. It edits Markdown, which by it's nature, is plain text. If others feel differently, please let me know.

**Comment by kristianlm** [comment]
Thanks for your feedback, Wes. I didn't really realize the relatively intrusive implications of this. I noticed this very comment-field has the same issue: I can't copy-paste text in this comment from my original post. For my target audience, however, I think I'll need to handle this properly.

For reference, [domador](https://github.com/bevacqua/domador) may worth checking out for people who want to look into this. I'll update this issue if I make that work!
