### ISSUE TITLE
Shift key is stuck, onScreen keyboard on iOS

### ISSUE THREAD

**Issue by ffffff101** [sparksuite/simplemde-markdown-editor#262]
When typing in a simple mde textbox, the shift key is stuck on uppercase, and the shift button must be pressed again to disable uppercase, rather than returning to lowercase automatically.

**Comment by WesCossick** [comment]
This appears to be an issue with CodeMirror, so you'll need to make an issue over there: https://github.com/codemirror/CodeMirror/issues.

CodeMirror is what powers SimpleMDE behind the scenes.
