### ISSUE TITLE
Is it possible to use the Browser Spelling Functionality?

### ISSUE THREAD

**Issue by JRawly** [sparksuite/simplemde-markdown-editor#267]
The spell check included is excellent. The only problem is that is it only available for American English.

The implementation we will be using has people from many different languages, and so we have had to disable the automatic spell checker.

However, the browser spellchecker does not work on the divs used to implement the MDE. Is is possible to enable this?

**Comment by WesCossick** [comment]
Short answer: no, unfortunately.

Longer answer: see https://github.com/codemirror/CodeMirror/issues/1017.
