### ISSUE TITLE
Single spaces do not work on default Samsung Keyboard Android

### ISSUE THREAD

**Issue by hiphigi** [sparksuite/simplemde-markdown-editor#268]
I only have Samsung devices to test, but I suspect it applies to all Androids, but I tested on a Galaxy S3, S4, and S5 and they all have the same issue. The issue is only with the default Samsung keyboard, when using a 3rd party keyboard it works fine (SwiftKey, etc).

When using the default Android/Samsung keyboard, if you hit the space bar once, nothing happens, but if you hit it twice, it gives you a single space. Basically, anytime you want to enter a space, you must first hit space bar twice. After you've hit it twice, it seems to work normally.

It appears to be an issue with the spell-checker in SimpleMDE, as the spell-check underline seems to lag when you do this as well.

I tested a standard textarea and several other jQuery richtext editors with the same devices and keyboard and the spacing worked fine as it normally should.

Trying to find a solution to this now. I'm not sure if there is a way to detect what keyboard a mobile user is using.

**Comment by WesCossick** [comment]
That is very bizarre. I don't have a Samsung device to test with, so I'll need to rely on you or someone else to find and fix this.

**Comment by WesCossick** [comment]
Thinking about it, this may be an issue with CodeMirror. Can you test to see if their [demo editor](https://codemirror.net/) has this issue? If so, it's better to create an issue in their repository.

**Comment by hiphigi** [comment]
This error does not occur on the code mirror demo.
- Dan L.

**Comment by hiphigi** [comment]
Any news or progress on this issue? Very big set back.

**Comment by WesCossick** [comment]
I have no way of testing or fixing this without a Samsung device. If you'd like to submit a PR, that'll probably be the only way this bug can be fixed.

**Comment by micwallace** [comment]
Wow this is a strange bug. The first space seems to be inserted initially but then deleted. I'll have a better look tomorrow.

**Comment by micwallace** [comment]
OK so the same issue IS present in CodeMirror.
You can close this issue, I'll resubmit it to the CodeMirror repo.

**Comment by Coffee2CodeNL** [comment]
This is still happening..
