### ISSUE TITLE
There is no obvious way to create a table for non-tec users.

### ISSUE THREAD

**Issue by COLABORATI** [sparksuite/simplemde-markdown-editor#270]
I assume this whole thing is done to enable non-tec users like grandma to edit things. 
But grandma has Libreoffice and she knows how to do tables, believe me.
Unfortunately grandma can not find any way to create or copy paste a table into this editor. 
She would be happy, if she had a way to import a csv file. 
I am now teaching her markdown - but then we do not need this editor anymore. Also she is laughing at me because she does not believe that tables with markdowns are so primitive, plus she just wants to copy-paste.
Conclusion: please do not stop development just because the most ultra-simplistic things are implemented - a product like this should also support tables.

**Comment by WesCossick** [comment]
There is a non-default [table toolbar icon](https://github.com/NextStepWebs/simplemde-markdown-editor#toolbar-icons) available. You can enable it with the `showIcons` setting.
