### ISSUE TITLE
Grammar check after load from save

### ISSUE THREAD

**Issue by arcs-** [sparksuite/simplemde-markdown-editor#271]
I noticed some little problems when using the spellchecker.
When closed and loaded back from save ( `autosave: { enabled: true}` ), the grammar won't be checked. When then I start to type, only the following text will be checked, not the things written above.

Also numbers from 0 - 9 are correct, but  every higher number (and lower) is wrong.

I also noticed that when writing code, sometimes it marks the indentation as wrong, but I can't make sense of it, it doesn't seem to have a clear pattern.

**Comment by WesCossick** [comment]
Can you create this issue at: https://github.com/NextStepWebs/codemirror-spell-checker/issues
