### ISSUE TITLE
Support for single-line inputs

### ISSUE THREAD

**Issue by nik-efimov-yyz** [sparksuite/simplemde-markdown-editor#272]
Hey everyone! Great project!

SimpleMDE works amazingly well for textareas, but I'm working on a project where we need to add markdown to one-line text inputs.

I can't seem to find a way to prevent the user from entering multiline text or hit Enter and move to the next line.

Is there a way to do this?

**Comment by WesCossick** [comment]
There's not (in my understanding), and I'm not sure if SimpleMDE would be a good fit for this. You may be able to fork and customize SimpleMDE to accomplish this.
