### ISSUE TITLE
readonly mode

### ISSUE THREAD

**Issue by christianmalek** [sparksuite/simplemde-markdown-editor#274]
Hi,

I want to use _simplemde_ not only for editing but also for rendering the markdown. Therefore i disabled the status and toolbar and changed the css to hide the border-lines. But unfortunately _simplemde_ doesn't understand, when I set the `readonly` attribute to a textarea. How can I achieve a `readonly`state?

**Comment by WesCossick** [comment]
Don't use SimpleMDE for simply rendering Markdown. Use another library, like https://github.com/chjj/marked (which happens to be the library SimpleMDE uses).

**Comment by DanielHreben** [comment]
I also need a read only mode, it is very usual option for every editor.
Use case: I need to show **rendered and source markdown both**, but do not allow editing until user click some button like "Copy and edit".

**Comment by TangentFoxy** [comment]
> I need to show rendered and source markdown both, but do not allow editing until user click some button like "Copy and edit".

So use Marked to render, and show the source next to it, then add a button with `onclick` to activate SimpleMDE with the textarea, or add a new textarea and hide the old, or whatever.

**Comment by artinboghosian** [comment]
The CodeMirror library already has support for readOnly option [Configuration](http://codemirror.net/doc/manual.html#config). Can't you allow passing that option from SimpleMde to CodeMirror?

**Comment by zmeireles** [comment]
I've created a wrapper of simplemde (I'm using Polymer), then accessed CodeMirror like this:.

`this.simpleMde.codemirror.options.readOnly = true;`

It works with me
