### ISSUE TITLE
Unable to write content at chrome 49

### ISSUE THREAD

**Issue by inhere** [sparksuite/simplemde-markdown-editor#279]
Unable to write any content in 49 chrome browser, press any key no response. In a demo(https://simplemde.com/) test, also will not work.

But in other browsers can work very well...

**Comment by danabrey** [comment]
No problem here on 49.0.2623.87 (64-bit).

**Comment by inhere** [comment]
I'm sorry, check carefully. And found a browser extensions affect editor work.
