### ISSUE TITLE
Hide markdown once valid in edit mode?

### ISSUE THREAD

**Issue by nod** [sparksuite/simplemde-markdown-editor#281]
Is it possible when in edit mode to hide the markdown syntax if the cursor is not on the word being editted?

Example:

If I am inputting the following:

```
this is my ***boomstick***
```

Once the cursor is no longer on "boomstick" it would look like

this is my **_boomstick**_

I tried to read through the docs and didn't see it as an option.

(I realize this is more of a feature request and I hope this is the right place for it.)

**Comment by WesCossick** [comment]
This is not possible. Similar concepts have been tried, but with the way CodeMirror functions, they do not result in a well polished end product.

**Comment by nod** [comment]
Very well.  You make me sad.  So be it.  Come, Patsy.
