### ISSUE TITLE
Long text adds empty space after exiting Side by Side mode

### ISSUE THREAD

**Issue by evenfrost** [sparksuite/simplemde-markdown-editor#288]
1. Go to demo page.
2. Enter reasonably long text (any text length will do, though long one is more descriptive).
3. Press 'Toggle Side by Side'.
4. Press 'Toggle Fullscreen'.

Result: Editor height is twice as big as text content. I believe Side by Side view duplicates it and does not revert.

**Comment by WesCossick** [comment]
This will be fixed in the next release.
