### ISSUE TITLE
spell checker

### ISSUE THREAD

**Issue by magnNorth** [sparksuite/simplemde-markdown-editor#292]
Couple things
1. NPM build issues
   `require("spell-checker");`
   seems to throw an error when compiling from the NPM build. Simply adding the full path works. 
   `require("codemirror-spell-checker/src/js/spell-checker.js");` 
   Not sure why we don't do that? 
2. NPM package dependancies
   In the build the spell check is pointing at the git repo. 
   On the NPM page its pointed at: https://www.npmjs.com/package/codemirror-spell-checker (404) 
   perhaps updating the NPM dep list? Just anther curve ball to chase.

**Comment by WesCossick** [comment]
Can you submit a PR for these changes?

**Comment by jjeffryes** [comment]
Changing it to require("codemirror-spell-checker"); also seems to solve the issue.

**Comment by jjeffryes** [comment]
The dependencies on codemirror in package.json also throw an error, currently they are 

"codemirror": "github:codemirror/CodeMirror",
"codemirror-spell-checker": "github:nextstepwebs/codemirror-spell-checker",

Shouldn't they be changed to version numbers?

Like 

"codemirror": "^5",
"codemirror-spell-checker": "^1",

**Comment by hiendv** [comment]
I'm experiencing the issue. Installing `github:nextstepwebs/codemirror-spell-checker` and `github:codemirror/CodeMirror` couldn't help.
