### ISSUE TITLE
Many console.log on init

### ISSUE THREAD

**Issue by prostoandrei** [sparksuite/simplemde-markdown-editor#296]
Many console.log on MDE initialization.
http://joxi.ru/ZrJyVBOh10w3wA
I that is not normal. I don't think that any developer wanna see this in console. Not in *.min.js version.

**Comment by Psykar** [comment]
Looks like #280 resolves this.
It's in development branch, but not in master yet.

**Comment by prostoandrei** [comment]
Yep, it's) Will be waiting master)
