### ISSUE TITLE
tabSize option does not take effect on Firefox

### ISSUE THREAD

**Issue by ksprwhite** [sparksuite/simplemde-markdown-editor#30]
I try setting like this:

```
indentWithTabs: false,
tabSize: 4
```

but don't work for me, check this: http://jsfiddle.net/kspr/rbkybz3b/ indentation is on 2 spaces.

EDIT: solved to me with:

`simplemde.codemirror.setOption('indentUnit', 4)`

**Comment by WesCossick** [comment]
The JSFiddle works for me:

![](http://i.imgur.com/LZLXI6z.gif)

What browser/OS are you using?

**Comment by ksprwhite** [comment]
I'm on firefox 38 / linux and the indentation is on 2 spaces always, is it a possible bug?

**Comment by WesCossick** [comment]
Okay, I can confirm it's not working for me either on Firefox. When I get a chance, I'll take a close look at the code to see if I can figure out why. Might be a bug with CodeMirror, in which case, I'll report it to them as well.

**Comment by WesCossick** [comment]
The issue has been fixed, it'll be included in the next release of SimpleMDE.
