### ISSUE TITLE
A way to hide markdown formatting.

### ISSUE THREAD

**Issue by VaelVictus** [sparksuite/simplemde-markdown-editor#302]
Right now if I were to bold some text, I would get `**Hello!**`. It would be bold, and also include the *\* around it. This is odd to me, and I think would confuse my users. I'd like to have it one way or the other:
1. Hitting bold simply makes the text **bold**
2. Hitting bold simply puts `**` around the word. (exactly like posting on github)

Of course I am talking about all formatting, not just bold. Is this possible?

**Comment by danabrey** [comment]
I think that this is one of the main features of SimpleMDE, and the very thing that makes it Simple. It makes it crystal clear to users exactly what each bit of Markdown markup does, and allows them to modify the formatting with ease. It _augments_ the editable text with Markdown formatting rather than _replaces_ it.

**Comment by VaelVictus** [comment]
My goal is to provide a box in which my users can chat with one another; it is _not_ my goal to teach people Markdown. SimpleMDE is a beautiful, minimal editor and I'd like to use it, so long as either of my issues could be resolved in some way. I'd like to see #1, but I expect #2 shouldn't be too hard to implement. If this goes against the purpose of simpleMDE, then I must move on, it seems.

**Comment by brondsem** [comment]
See prior discussions in #281 and #232

**Comment by VaelVictus** [comment]
RIP. Sorry I missed these two, especially when they're so recent.

Those who are looking for something with the heart of SimpleMDE but with features such as these, check out Pagedown. https://pagedown.googlecode.com/hg/demo/browser/demo.html

**Comment by Hariharansudanhhs20** [comment]
I need to disable the character formatting.
E.g 
    Same to GitHub editor "** Bold **".

**Comment by Hariharansudanhhs20** [comment]
I will add the underline button. So how to apply the formatting in a new underline button.
