### ISSUE TITLE
Fontawesome

### ISSUE THREAD

**Issue by RishabSwift** [sparksuite/simplemde-markdown-editor#305]
Hi,

I have laravel and I'm compiling the simplemde.min.js file to a main 'script.js' file  and same with the css.

I already have Font awesome in my main.css file merged with many other files including simplemde.css. But it still uses the CDN version of font-awesome.

How can I fix this?

**Comment by forsureitsme** [comment]
Set the configuration variable **autoDownloadFontAwesome** to `false`, as explained in the [Configuration section](https://github.com/NextStepWebs/simplemde-markdown-editor#configuration).
