### ISSUE TITLE
turn off console output

### ISSUE THREAD

**Issue by ciel** [sparksuite/simplemde-markdown-editor#312]
Is there a way to disable all of the console output SimpleMDE generates? It writes a ton of things even with the minified file.

**Comment by HexMox** [comment]
same problem

**Comment by ciel** [comment]
I solved it with this line in my `gulpfile`. If you're using any sort of task manager, you may be able to do the same.

`.pipe(replace(/(?:console.log\((?:.*)\);)/gmi, ''))`

**Comment by WesCossick** [comment]
Duplicates of #280 and #284.
