### ISSUE TITLE
YAML Frontmatter

### ISSUE THREAD

**Issue by PhrozenByte** [sparksuite/simplemde-markdown-editor#314]
First of all: Great software! :+1:

SimpleMDE should support formatting YAML Frontmatters (possibly after setting a config variable). YAML Frontmatters are often used by flat-file CMS like [Pico](http://picocms.org/), [Grav](https://getgrav.org/) or [Jekyll](https://jekyllrb.com/) to store meta data of a specific page. CodeMirror already comes with both a [YAML](https://codemirror.net/mode/yaml/index.html) and [YAML Frontmatter](https://codemirror.net/mode/yaml-frontmatter/index.html) mode.

``` yaml

---
foo: bar
baz:
    - Hello
    - World

---

SimpleMDE
=========

Lorem ipsum...
```

**Comment by WesCossick** [comment]
SimpleMDE is purely a Markdown editor. If you'd like to fork SimpleMDE and convert it into some other type of formatting, you are welcome to do so.

**Comment by PhrozenByte** [comment]
Does SimpleMDE provide a way to hook into its processing without forking the project in whole (and therefore fragmenting your user base)?

**Comment by WesCossick** [comment]
SimpleMDE (the MD stands for Markdown) only focuses on Markdown. I have no plans of changing this.

**Comment by PhrozenByte** [comment]
Yeah, that's completely fine and I don't want to change anything about it if you don't want to, but that wasn't my question :wink: :smile:

I was asking you about any suggestions about _how_ **I** can hook into SimpleMDE's processing to add the wished functionality _without_ forking SimpleMDE - i.e. some sort of API. The goal is to leave SimpleMDE itself completely untouched and just extend its functionality _from the outside_ (like SimpleMDE's `previewRender` option/hook). Forking SimpleMDE fragments the user base and is something I would like to avoid, so I'm asking you about possible different approaches without forking the project in whole.

If SimpleMDE currently doesn't provide a way to do something like this, I would like to participate in developing some sort API to extend SimpleMDE without forking the project. So I'm asking you about maybe already existing approaches or ideas about how to achieve this :smiley:

**Comment by mirbatworks** [comment]
Hello WesCossick, is it posible to add css class to image in editor?If it is, please tell me how to do it, if not, it will be very nice if you add this possibility. Thanks.

**Comment by WesCossick** [comment]
@PhrozenByte At the moment there is no way to adjust the processing of SimpleMDE. You can replace the preview rendering function though.

**Comment by mirbatworks** [comment]
Is it possible to add css class tom image?

**Comment by PhrozenByte** [comment]
@WesCossick, so, if I open a PR implementing hooks to allow adjusting SimpleMDE's processing, will you accept it (i.e. generally speaking, do you like the idea of hooking into SimpleMDE's processing)?

**Comment by WesCossick** [comment]
Can you elaborate more on what you'd plan on changing?

**Comment by PhrozenByte** [comment]
I didn't thought about a concrete solution yet, you didn't say anything whether this even comes into question or not. However, this is prerequisite to follow up with SimpleMDE's source code and to evaluate possible solutions. It isn't mandatory for my personal use case to implement this, I could also use a second textarea just for YAML. However, I think SimpleMDE profits by a sane way to hook into its processing, so I'm willing to implement it - as long as you're interested in something like this. I don't want to waste my time with programming something you don't want - I really have no interest in forking SimpleMDE.

My first idea is to add a `markdownRender` callback (like the existing `previewRender` callback) that allows you to add a new CodeMirror mode (with `CodeMirror.overlayMode()`) and let SimpleMDE use this mode instead of `gfm` resp. `spell-checker`.

**Comment by WesCossick** [comment]
I'm not very interested in this for SimpleMDE to be honest. I'd like to stick to just Markdown to keep things simple.

**Comment by PhrozenByte** [comment]
Alright, I'll do the workaround with two textareas then. Thanks for your help anyway! :+1:
