### ISSUE TITLE
Cannot _modify_ toolbar

### ISSUE THREAD

**Issue by Sleavely** [sparksuite/simplemde-markdown-editor#317]
I'm missing a method to re-render the toolbar or access the default values for it.

`createToolbar` isn't applicable because it literally creates a new toolbar, leaving the first toolbar intact.

In Lepture's editor I could do the following to inject a button to the existing toolbar without completely overwriting it. It's not super-gracious but it works:

``` javascript
var myEditor = new Editor();
myEditor.options.toolbar.splice(8, 0, {
  action: function(){
    // Custom logic here.
    editor.codemirror.doc.replaceSelection('Some cool markdown syntax');
  },
  name: 'customActionIdentifier'
});
myEditor.render();
myEditor.codemirror.focus();
```

In SimpleMDE it's not that simple. I can't tell if its because `render()` does nothing or because the options object is ignored upon rendering. Either way, the editor requires me to want to know exactly how the toolbar should look before I initialize:

``` javascript
var myEditor = new SimpleMDE();

myEditor.options.toolbar.splice(10, 0, {
  name: 'customActionIdentifier',
  action: function(simplemde){
    simplemde.codemirror.doc.replaceSelection('Some cool markdown syntax');
  },
  className: 'super-cool-custom-icon-class-thing',
  title: 'My awesome Action'
});

var theToolbarIReallyWant = myEditor.options.toolbar;
myEditor.toTextArea();
myEditor = null;

myEditor = new SimpleMDE({
  spellChecker: false,
  toolbar: theToolbarIReallyWant
});
```

As you can see, I have to initialize the editor twice. Once to be able to read the toolbar array and once to render it with my modified toolbar. My proposition is that you make available the default toolbar actions so that the array can be modified **before** rendering.

Perhaps something along these lines?

``` javascript
var theToolbarIReallyWant = SimpleMDE.prototype.defaults.toolbar;
theToolbarIReallyWant.splice(10, 0, {
  name: 'customActionIdentifier',
  action: function(simplemde){
    simplemde.codemirror.doc.replaceSelection('Some cool markdown syntax');
  },
  className: 'super-cool-custom-icon-class-thing',
  title: 'My awesome Action'
});

// Initialize once.
myEditor = new SimpleMDE({
  spellChecker: false,
  toolbar: theToolbarIReallyWant
});
```

**Comment by WesCossick** [comment]
Duplicate: #252
