### ISSUE TITLE
a mode with hidden markups

### ISSUE THREAD

**Issue by aahoo** [sparksuite/simplemde-markdown-editor#319]
I've been looking for a WYSIWYG editor like TinyMCE that uses Markdown under the hood. Not having the Markdown syntax hidden makes it easier to combine editing and reading. No need to have to UI elements one for editing and one for previewing. Instead of typing the markups, toolbar or keyboard shortcuts could be used. If anyone in the dev team is interested, I can spare some time to contribute.

**Comment by WesCossick** [comment]
Duplicates of #302, #281, and #232
