### ISSUE TITLE
Adding class and id to image?

### ISSUE THREAD

**Issue by mirbatworks** [sparksuite/simplemde-markdown-editor#322]
Will you considering possibility that user can add custom class and id to image? Now is only possible to add image url and alt.

**Comment by WesCossick** [comment]
Markdown does not support more than the `alt` tag and the URL.

**Comment by hootlex** [comment]
You can use [Markdown Extra](https://en.wikipedia.org/wiki/Markdown_Extra) to add classes.

**Comment by prvn3294** [comment]
@hootlex  , can you post any example. how to add a class to img tag in simpleMDE using markdown extra
