### ISSUE TITLE
Codemirror Themes possible?

### ISSUE THREAD

**Issue by lmajano** [sparksuite/simplemde-markdown-editor#323]
Is it possible to use codemirror themes?

**Comment by WesCossick** [comment]
Not currently, but you can add styling to SimpleMDE using CSS.

**Comment by xcatliu** [comment]
Hi, I've built a theme system for SimpleMDE, it's easy to create your own theme. Hope this would help you!

- [SimpleMDE Theme Base](https://github.com/xcatliu/simplemde-theme-base)
- [SimpleMDE Theme Dark](https://github.com/xcatliu/simplemde-theme-dark)
- [List of themes](https://github.com/xcatliu/simplemde-theme-base/wiki/List-of-themes)

Related issue: #498
