### ISSUE TITLE
Unable to input Chinese character in mobile

### ISSUE THREAD

**Issue by jet10000** [sparksuite/simplemde-markdown-editor#325]
iphone6s, chrome

Unable to input Chinese character in mobile

![image](https://cloud.githubusercontent.com/assets/2258120/15242136/013f5c22-1927-11e6-8b89-d39789b6c2d1.png)
![image_k9zexpi](https://cloud.githubusercontent.com/assets/2258120/15242137/013f69f6-1927-11e6-9dcd-ea64df51a4ae.png)

**Comment by jet10000** [comment]
https://github.com/codemirror/CodeMirror/issues/3137

**Comment by WesCossick** [comment]
@jet10000 is this an issue with CodeMirror specifically?

**Comment by kxgio** [comment]
Same issue here, with Bopomofo input.
