### ISSUE TITLE
Bower package should include non-minified files

### ISSUE THREAD

**Issue by koenpunt** [sparksuite/simplemde-markdown-editor#326]
![image](https://cloud.githubusercontent.com/assets/351038/15244180/2c19adf2-1900-11e6-943c-0f335eb0bc15.png)

**Comment by WesCossick** [comment]
Would you like to submit a PR for this change?

**Comment by PascalPixel** [comment]
Yes but not ES6 files that are uncompiled, you'll need a step in-between at least
