### ISSUE TITLE
Which codemirror version are you using?

### ISSUE THREAD

**Issue by greenlaw110** [sparksuite/simplemde-markdown-editor#327]
I am trying to integrate simplemde with another codemirror based product: https://github.com/Rovak/InlineAttachment/ which use codemirror v3.24.0, however it looks like the version is not compatible with simplemde and I got this error:

![image](https://cloud.githubusercontent.com/assets/216930/15267944/27e54be2-1a13-11e6-84ea-30a21c63ee9c.png)

Here is the jsfiddle to reproduce the issue: https://jsfiddle.net/afrbct50/

**Comment by WesCossick** [comment]
SimpleMDE uses the very latest version of CodeMirror at build-time. It'll be version 5+.
