### ISSUE TITLE
open link in new tap

### ISSUE THREAD

**Issue by abdtif** [sparksuite/simplemde-markdown-editor#329]
Hi

how to make the link open in new tap ??

[test](http://)

**Comment by sezertunca** [comment]
+1

**Comment by WesCossick** [comment]
The default Markdown parsing engine online opens links in the same tab. You can, however, modify the Markdown parsing engine using the `previewRender` option.

**Comment by abdtif** [comment]
previewRender option.  ???

i am not a programer
