### ISSUE TITLE
New custom markup

### ISSUE THREAD

**Issue by carportar** [sparksuite/simplemde-markdown-editor#331]
hello, I want to create an action that allows me to directly insert an embedded video, not thumnail , or html with a specific class.

**Comment by WesCossick** [comment]
Take a look at the `previewRender` option. It'll let you create your own custom rendering engine.

**Comment by carportar** [comment]
Thank colleague I will review , if you can help me with an example would be better for since I'm a rookie.

**Comment by WesCossick** [comment]
There are multiple examples in the README.
