### ISSUE TITLE
Support grammar checking

### ISSUE THREAD

**Issue by awildeep** [sparksuite/simplemde-markdown-editor#333]
NOTE: This may already be something that can be added into simplemde, I just don't see how it could be done effectively.

I am looking to modify simplemde and use https://github.com/nlp-compromise/nlp_compromise to provide grammar rules and suggest document rewrites similarly to how http://www.hemingwayapp.com/ provides feedback on run-on sentences, adverbs, and passive voice.

My first thought was to use the "on-change" event and modify the dom of the editor window and wrap text in classes that I could then decorate. I've since found this to be a dead end.  It looks like I need to modify how the editor applies it's markup, but I am not seeing an easy way to do that currently.

Any suggestions?

**Comment by WesCossick** [comment]
You'd need to fork the project to do this, but you could use the overlay ability from CodeMirror to add a new mode. That's probably best. For more assistance with this, see CodeMirror's documentation and refer to StackOverflow.
