### ISSUE TITLE
Is there a way for priview-mode only?

### ISSUE THREAD

**Issue by amanuel2** [sparksuite/simplemde-markdown-editor#335]
I was just asking if there is a way for prieview mode only.... So the user cant edit.

**Comment by WesCossick** [comment]
Don't use SimpleMDE, an editor, for just previewing. Use a Markdown parser instead.

**Comment by yuchunc** [comment]
Hi @WesCossick what if I already have SimpleMD in the packaged js file. Is there some way I can use it's internal markdown parser? 

This would make the parsing more consistent, and I don't have to bring in another parser.
Thank you!

**Comment by WesCossick** [comment]
@yuchunc Sure, if you'd like, you can do the following:

```JS
simplemde.options.previewRender("This is *example* Markdown");
```

**Comment by yuchunc** [comment]
@WesCossick ah~ simple enough.
Thank you for the information!
