### ISSUE TITLE
console.log()'s from simplemde.min.js

### ISSUE THREAD

**Issue by jkurei** [sparksuite/simplemde-markdown-editor#337]
I'm using simplemde through benrlodge's [react wrapper ](https://github.com/benrlodge/react-simplemde-editor), which pulls the minified version. My application has to spawn several editors on demand, and every time I get a ton of console.log messages comming from `simplemde.min.js`. 

Isn't it a bad idea to have these, at least in a "production" version (if its minified, you're not coding on it)?

<img width="1359" alt="screen shot 2016-05-26 at 12 27 43" src="https://cloud.githubusercontent.com/assets/1428611/15571860/abb6bf7c-233d-11e6-8701-1138d173e996.png">

**Comment by Voziv** [comment]
Seems like it's already been removed, see #316 

Just waiting for the next version to be released.

As another person mentioned in #312 you can use gulp or another task manager to replace the console.log statements until the next version gets released

Edit: I came here for the same issue of getting rid of the console.log output

**Comment by jkurei** [comment]
hum, i missed those, should've looked at closed issues too. Thanks!
