### ISSUE TITLE
Is there any way to use spell checking build in browser?

### ISSUE THREAD

**Issue by JG24** [sparksuite/simplemde-markdown-editor#338]
Hello. Sorry for my English. I disable spell checking by spellChecker: false. How enable default spell checking build in eg. Firefox browser? I try add spellcheck="true" to <textarea> but it doesn't work.

**Comment by WesCossick** [comment]
It's not possible to integrate with the browser's spell checker, unfortunately. See: https://github.com/codemirror/CodeMirror/issues/1017
