### ISSUE TITLE
Toolbar fixed

### ISSUE THREAD

**Issue by Lec2cn** [sparksuite/simplemde-markdown-editor#340]
When the page scroll down , i can't see the toolbar anymore.
So i think it's better to add an option to let the toolbar [position:fixed] when i scroll down.

**Comment by gbaumgart** [comment]
same here

**Comment by TangentFoxy** [comment]
@WesCossick Why was this rejected?

**Comment by WesCossick** [comment]
@Guard13007 This is something that can be added on the developer's end with a line or two of CSS. I don't think this is necessary to build into SimpleMDE, unless it were a configurable option and the toolbar was sticky, not fixed.
