### ISSUE TITLE
Bug in preview data display

### ISSUE THREAD

**Issue by prostoandrei** [sparksuite/simplemde-markdown-editor#341]
In editor

```
**Bold**
*Italic*
```

rendered as 

```
<p>
  <strong>asd</strong>
  <br>
  <em>asd</em>
</p>
```

But it should be

```
<p>
  <strong>asd</strong>
  <em>asd</em>
</p>
```

Data stored correctly. But in preview we have a bug.

**Comment by prostoandrei** [comment]
Sorry it's not a bug.

Need to set

```
renderingConfig: {
  singleLineBreaks: false
},
```

But i have misunderstood why it settled default to true.
Because of this, it seems like library have a bug .

**Comment by danabrey** [comment]
In a WYSIWYG-style editor, this:

```
**Bold**
*Italic*
```

...implies that you want a line break to be inserted between the two lines. You can change that default behaviour with the configuration option you mention.

**Comment by prostoandrei** [comment]
@danabrey 
But markdown is not WYSIWYG.
For exmaple if you send

```
**Bold**
*Italic*
```

and server and it should convert somewhere you will be surprised. Because preview !== realConvertedMarkdown

**Comment by amanuel2** [comment]
Guys is there a preview mode only?

**Comment by WesCossick** [comment]
GitHub Flavored Markdown is the variant used for SimpleMDE. It supports single line breaks.

More than that, SimpleMDE is designed for users who are not familiar with Markdown. Not supporting single line breaks would no doubt confuse this type of user.

**Comment by prostoandrei** [comment]
@WesCossick  ok, thank you for explanation.

But still it was a bit strange to see different code in the preview, and output :)
