### ISSUE TITLE
help: toolbar icon element....

### ISSUE THREAD

**Issue by lxepoo** [sparksuite/simplemde-markdown-editor#342]
Why Font Awesome in `<a class="fa fa-bold"></a>`

resulted in the toolbar displays the □□□□□□□□□□□□, how to use `<i = "Fa fa-bold" >`?

**Comment by lxepoo** [comment]
now work js:

```
        $('.editor-toolbar > a').each(function (index, ele) {
            var old_class = $(ele).attr('class');
            $(ele).html('<i class="' + old_class + '"></i>').attr('class', '');
        });
```

but [preview] is bad

**Comment by lxepoo** [comment]
hi~

 is there a better solution? Or is the next version going to solve this problem?

**Comment by WesCossick** [comment]
You'll need to submit a JSFiddle that replicates this error. Seems like it's a problem on your end currently.
