### ISSUE TITLE
Remove unnecesary console messages

### ISSUE THREAD

**Issue by diegograsso** [sparksuite/simplemde-markdown-editor#343]
This editor is great. Please remove the messages from the console here:

https://github.com/NextStepWebs/simplemde-markdown-editor/blob/master/src/js/simplemde.js#L1675

and here

https://github.com/NextStepWebs/simplemde-markdown-editor/blob/master/src/js/simplemde.js#L1677

Thanks!

**Comment by mertkahyaoglu** [comment]
👍

**Comment by diegograsso** [comment]
I see that this is already fixed in development branch with other fixes that I would also like to have. When is the next release date planned? Could you release current fixes please?
