### ISSUE TITLE
 CodeMirror is not defined....when i use simplemde with webpack

### ISSUE THREAD

**Issue by Archao-ME** [sparksuite/simplemde-markdown-editor#358]
when i use it to my code with webpack, there first problem is : 

> Module not found: Error: Cannot resolve module 'fs'

and i fixed it in webpack config file..with add 

```
  node: {
    fs: "empty"
  },
```

But now it show error like that : 

> spell-checker.js?5142:19Uncaught ReferenceError: CodeMirror is not defined

how can i fix it??

**Comment by robbieaverill** [comment]
Duplicate of #355
