### ISSUE TITLE
Image & quote toolbar icons

### ISSUE THREAD

**Issue by fraserredmond** [sparksuite/simplemde-markdown-editor#36]
Was just playing around with the new toolbar settings (thanks for that!) and found something odd.

```
    var simplemdeObj = new SimpleMDE({
        element: byId("<?=$name?>"),
        status: false,
        lineWrapping: true
    });
    console.log(simplemdeObj.toolbar);
```

In the console output there is no property for image, and the object inside quote is actually the image button.

**Comment by WesCossick** [comment]
I believe this is due to when the toolbar is being created in [this file](https://github.com/NextStepWebs/simplemde-markdown-editor/blob/master/source%20files/simplemde.js#L617), it is overwriting the toolbar variable. I'll fix this in the next release.

**Comment by WesCossick** [comment]
Fixed in [this commit](https://github.com/NextStepWebs/simplemde-markdown-editor/commit/1aad2dec4c9236a83f20bc92a2660434ac749e19)
