### ISSUE TITLE
Move bower.json main paths to dist not src

### ISSUE THREAD

**Issue by gorgekara** [sparksuite/simplemde-markdown-editor#360]
Not sure if on purpose or not but you've set your main bower file paths to come from the /src path. This is OK and works most of the time, but when i try to build it with grunt bower concat it uses these files.

Can you please move

`"main": ["src/js/simplemde.js", "src/css/simplemde.css"],`

to 

`"main": ["dist/simplemde.min.js", "dist/simplemde.min.css"],`

If it's too big of an issue i'll fork this repo and move it.

PS: For some reason when i'm setting different bower concat main path it's not working.

**Comment by horaciogiovine** [comment]
im too having this issue, but i had fixed it manually. a fix would be awesome!

**Comment by WesCossick** [comment]
See the spec: https://github.com/bower/spec/blob/master/json.md#main

> Do not include minified files

**Comment by fkamras** [comment]
I have the same issue. I get required is not defined when trying to update to 1.11

**Comment by noclat** [comment]
Then maybe have not minified but still compiled and working files? You don't link SCSS or LESS stylesheets, why link uncompiled JS?

**Comment by PascalPixel** [comment]
This is really an issue, simplemde is now not compatible with anything ES5, like Rails

It is not about providing the minified files, those Bower rules probably don't take the ES6 world into account?

**Comment by WesCossick** [comment]
Per the spec:

> Entry-point files have module exports and may use module imports. While Bower does not directly use main files, they are listed with the commands `bower list --json` and `bower list --paths`, so they can be used by build tools.

If you would to see a change in SimpleMDE, you'll need to request that Bower update their specifications. We follow Bower's published documentation.
