### ISSUE TITLE
SimpleMDE not Defined

### ISSUE THREAD

**Issue by dillonco** [sparksuite/simplemde-markdown-editor#363]
I was using everything fine yesterday but started getting this error today. I checked it out on your demo page (https://simplemde.com/) and I'm getting the same error.

```

ReferenceError: CodeMirror is not defined
ReferenceError: SimpleMDE is not defined
```

Checked with Firebug on Firefox and on Chrome.

[Screenshot ](http://i.imgur.com/8m6YPF1.png)

**Comment by bituser** [comment]
I can confirm that I am receiving this error on both my site and the demo site. The demo site doesn't have a interactive form at all. This doesn't seem related to ad block. Perhaps a recent change has broken the entire application.

EDIT: This appears to have been resolved.

**Comment by WesCossick** [comment]
Duplicate #355

**Comment by toplyb** [comment]
In vue, I want to put the Markdown article analysis to the page, in the use of the prototype chain simplemde method namely `SimpleMDE.prototype.markdown(content)`, display simplemde is not defined, please advise the should deal with this situation

**Comment by ProNotion** [comment]
> In vue, I want to put the Markdown article analysis to the page, in the use of the prototype chain simplemde method namely `SimpleMDE.prototype.markdown(content)`, display simplemde is not defined, please advise the should deal with this situation

Did you ever resolve this?
