### ISSUE TITLE
Toolbar buttons for h1, h2, h3, hr

### ISSUE THREAD

**Issue by fraserredmond** [sparksuite/simplemde-markdown-editor#37]
Toolbar buttons for h1, h2, h3, hr

**Comment by WesCossick** [comment]
`hr` button is already an option. See: https://github.com/NextStepWebs/simplemde-markdown-editor#toolbar-icons

Header buttons will be added soon.

**Comment by WesCossick** [comment]
Upon further consideration, I'm going to pass on the h1, h2, h3, etc. buttons. Font Awesome does not offer icons for each of these; they only have one header icon–which isn't even that recognizable.

If you are still interested, you can use the [toolbar option](https://github.com/NextStepWebs/simplemde-markdown-editor#toolbar-icons) to create your own buttons and have the action be a function of your own. Just model it after the functions in the `simplemde.js` file.

**Comment by fraserredmond** [comment]
Ok, fair enough :)

One question on reorganising the toolbar icons - do I have to put in the full settings for each button (like the example code), or is there some shorter way to indicate which ones to put in? E.g. something like:

```
var simplemde = new SimpleMDE({
    toolbar: ["bold", "italic", "|", "hr", ... ]
});
```

If it has to be the full settings, it'd be handy to have an example of all the buttons not in the readme.md, but in some other file to be copied from.)

**Comment by WesCossick** [comment]
This will replace the toolbar variable, so all the settings are necessary. The full list of default buttons is located here: https://github.com/NextStepWebs/simplemde-markdown-editor/blob/master/source%20files/simplemde.js#L388

**Comment by fraserredmond** [comment]
Thanks Wes.

One last suggestion on this - Font Awesome has a class to make icons a little bigger, which means you could use the heading icon like this to do H1 and H2:

```
"|",
{
    name: "h1",
    action: toggleH1,
    className: "fa fa-header fa-lg",
    title: "Heading 1 (Ctrl+H)",
},
{
    name: "h2",
    action: toggleH2,
    className: "fa fa-header",
    title: "Heading 2 (Ctrl+Alt+H)",
},
"|",
```

The H1 & H2 really ought to use _toggleLine (I'm using toggleBlock at the moment), but that then means changing simplemde, so thought I'd see if I could persuade you :-)

They could be left off by default, like the horizontal-rule, if you really hate the Heading icon ;-)

My application happens to use h1 and h2 more than any other tags, so that's why I'm so keen to have it.

**Comment by WesCossick** [comment]
Can you show me a screenshot of what those two header icons look like in the toolbar?

Also, have you written the toggleH1/toggleH2 functions? If so, you could make a pull request and I'll consider merging it in as an available button that isn't active by default.

**Comment by nofxx** [comment]
Don't remember where I've saw it but I think it's a nice idea:
Only one button 'H' (the fa-header).  Clicking on it loops the cursor current line phrase: h1, h2, h3, h4, h5, h6, h1, ... ( or actually #, ##, ### ... #, ... )
It's intuitive and doesn't clutter the toolbar imho.

**Comment by fraserredmond** [comment]
Yeah, I'd thought the same on clicking a heading multiple times... but my users would find the 2 buttons easier.

I'll make a pull request for the 2 buttons, then you can decide from there. If you take it back down to one button, I'd suggest Ctrl+Shift+H to change heading size in opposite direction. (Or you could keep the 2 buttons, and make another called 'toggle-heading'.)

Here's how the 2 buttons look:

![image](https://cloud.githubusercontent.com/assets/1796533/9204780/92aeca4e-4056-11e5-965b-47e660fc23ba.png)

**Comment by WesCossick** [comment]
Okay, I'm liking the cycling through idea. But I'll take a look at your PR @fraserredmond and see if I can modify it to behave in the best way possible using both of y'all's suggestions.

**Comment by WesCossick** [comment]
Completed with #53

**Comment by madmax** [comment]
You can easly make nice h1 icon using font-awesome:

http://mad.xan.pl/s/1GoHSZQ77L/

```
className: "fa fa-header fa-header-1",
.fa-header-1:after {
  font-size: 50%;
  vertical-align: text-bottom;
  content: "1";
}
```
