### ISSUE TITLE
Include builds which doesn't contain 3rd-party contents

### ISSUE THREAD

**Issue by breezewish** [sparksuite/simplemde-markdown-editor#375]
For JavaScripts, provide a build which doesn't contain marked.
For CSS, provide a build which doesn't contain CodeMirror styles.
This prevents duplicates when SimpleMDE is used as a part of a system (for example, webpack), in which those 3rd-party contents are already included.

**Comment by WesCossick** [comment]
Although this would prevent duplicates, because SimpleMDE is all bundled together into one JS and one CSS file (not making multiple HTTP requests), the performance gain would be minute.
