### ISSUE TITLE
Image action with incorrect cursor position (v1.11.2)

### ISSUE THREAD

**Issue by marizmelo** [sparksuite/simplemde-markdown-editor#377]
on version v1.11.2
Maybe it is just me but If I include an image on the editor the following syntax is being inserted:

```
"![](", "http://)"
```

instead of:

```
"![](http://", ")"
```

In my case I removed the "http://" completely since I usually copy and paste urls from the browser url bar.

**Comment by WesCossick** [comment]
This has to do with the way other settings work, like the one that prompts for user input for the URL. I hope to improve this in version 2 of SimpleMDE.
