### ISSUE TITLE
Add custom css class for editor-preview 

### ISSUE THREAD

**Issue by elsuxo** [sparksuite/simplemde-markdown-editor#379]
Is there a way to add a custom css class to the editor-preview?

**Comment by WesCossick** [comment]
At this time, there is not. It comes standard with the `editor-preview` class.

**Comment by Jigsaw5279** [comment]
Will this ever become a thing? It's quite handy if you already have styles defined for a specific container, so it will actually look like the preview when rendered there.

**Comment by margani** [comment]
I did this by overriding previewRender:
```js
      previewRender: (plainText, previewArg) => {
        const preview = previewArg;
        setTimeout(() => {
          preview.innerHTML = `
            <div class="content">${marked(plainText)}</div>
          `;
        }, 1);

        return `Loading...`;
      }
```
