### ISSUE TITLE
Floating toolbar

### ISSUE THREAD

**Issue by lukasoppermann** [sparksuite/simplemde-markdown-editor#380]
Hey, are there any plans of adding a floating version of the toolbar, that just shows up when the cursor is in the textarea and selecting something.

I wrote something like this: http://lukasoppermann.github.io/mark/ but the code is very, very bad. Instead of rebuilding it, I would much rather use your solution, but I need a floating toolbar, because I have many and partly small editor instanced. Having so many permanent toolbars would look weird and not work for small instances.

**Comment by WesCossick** [comment]
At the moment, I have no plans of implementing a floating toolbar. But I can certainly flag this as an idea.

**Comment by lukasoppermann** [comment]
Ahh, okay. I guess it should not be to hard, right? All you need to do is write the logic for positioning it.
