### ISSUE TITLE
Web component

### ISSUE THREAD

**Issue by lukasoppermann** [sparksuite/simplemde-markdown-editor#381]
Another question. Are there any plans to turn this into a web component? (Or better, to also provide it as a web component)?

**Comment by WesCossick** [comment]
I'm not sure if I know what you mean by "web component." Can you elaborate?

**Comment by lukasoppermann** [comment]
Hey @WesCossick, web components are an emerging standard for creating easy to use and share elements. All major browser agreed on the specs.

http://webcomponents.org/

The awesome thing is, that a user would just need to add a simple `<simple-mde></simple-mde>` tag to her page to get an editor instance.

**Comment by WesCossick** [comment]
It seems to me like web components still need a script to be loaded, but instead of writing `<textarea></textarea>`, you'd write `<simplemde></simplemde>`. I see very little benefit in that.

**Comment by lukasoppermann** [comment]
Well, all config and the script can actually be embedded in the script. The css can also be embedded, so in fact you only have to import 1 html file and can start using the editor.

**Comment by WesCossick** [comment]
Well I'm open to the idea, but I'm not sure if it'll take priority over other features.

**Comment by jpdevries** [comment]
I don't see much benefit either because `<textarea>` is backwards compatible, progressively enhanced. Can you do that with `<simplemde>`?
