### ISSUE TITLE
Confusion with css in project

### ISSUE THREAD

**Issue by asvae** [sparksuite/simplemde-markdown-editor#384]
In project we have 3 css files:
- `src/css/simplemde.css`
- `debug/simplemde.css`
- `build/simplemde.min.css`

I'm doing my automated build and I want full (not minified) version. So I included 'src/css/simplemde.css'. That should work as it does in assortment of different libraries, right? No, it doesn't. Cursor doesn't appear and editor becomes mostly unusable.

The point is, you probably want to either toss both minified and full versions into build folder, or have full css in `src` folder. Because `debug` folder is not the place other people will be looking for stable bundle in the package.

**Comment by WesCossick** [comment]
Other CSS files are bundled into the project during the build process. If you want the bundled, unminified version, see the `/debug/` folder.

**Comment by asvae** [comment]
@WesCossick I figured where files are located. The point is it's confusing for many people.
Take a look on where css is located in other libraries (e.g. font-awesome, bootstrap and many others).

**Comment by sebastiaanluca** [comment]
I agree, would save us some time if the source files and their use were explained in the readme or so. `Debug` makes me think of incomplete files used for testing or as scratch files.
