### ISSUE TITLE
Is it possible to add custom highlighting to the editing window?

### ISSUE THREAD

**Issue by Flibio** [sparksuite/simplemde-markdown-editor#385]
Hello,

Is it possible to add custom highlighting to the editing window? For example, say I modify the markdown preview to parse any text surrounded by `%` to be displayed orange. Similar to how text in `**` is displayed bold, could I also modify the editing preview to display the text in `%` orange?

**Comment by WesCossick** [comment]
Unfortunately I don't believe it's possible, not without reworking CodeMirror's code.

**Comment by Flibio** [comment]
Ah, that's a shame. Thanks anyways!
