### ISSUE TITLE
"Can't find variable: require"

### ISSUE THREAD

**Issue by coneybeare** [sparksuite/simplemde-markdown-editor#387]
![screen shot 2016-07-18 at 3 41 02 pm](https://cloud.githubusercontent.com/assets/35369/16927950/24d962da-4cfe-11e6-8134-364895b9fcbb.jpg)

I am trying to install this using [rails-assets](https://rails-assets.org), a thin wrapper around bower that preps for Rails environments. What is `require` and why do you expect it to be defined in all scenarios?

**Comment by WesCossick** [comment]
It looks like you're using the source code, not the bundled code for production use. See this file instead: https://github.com/NextStepWebs/simplemde-markdown-editor/blob/master/dist/simplemde.min.js

**Comment by PascalPixel** [comment]
Because the source code is pointed to in the bower.json
