### ISSUE TITLE
Show Images

### ISSUE THREAD

**Issue by tillkruss** [sparksuite/simplemde-markdown-editor#389]
Is there a way to show images as a rendered `<img>` element?

**Comment by WesCossick** [comment]
The preview does render images. Is that not what you're looking for?

**Comment by tillkruss** [comment]
I was think right in the editor, similar to WordPress.

**Comment by WesCossick** [comment]
That might be a bit too complex for CodeMirror to handle, which is the backbone of this project. Really, SimpleMDE is into making Markdown text look understandable, not actually rendering anything before previewing.

**Comment by tillkruss** [comment]
Thanks for the explanation!
