### ISSUE TITLE
Rerender preview when setting value

### ISSUE THREAD

**Issue by hansottowirtz** [sparksuite/simplemde-markdown-editor#399]
While creating simplemde-angular, I noticed the preview is not rerendered when setting the value. I think after line 1873, there should be code like this:

``` javascript
if (this.isPreviewActive()) {
  var wrapper = cm.getWrapperElement();
  var preview = wrapper.lastChild;
  preview.innerHTML = editor.options.previewRender(val, preview);
}
```

If you're not doing this, please expose a rerenderPreview function.

**Comment by WesCossick** [comment]
Do you want to submit a PR with this fix?

**Comment by TangentFoxy** [comment]
Shouldn't this issue be closed?
