### ISSUE TITLE
Very hard to edit on mobile

### ISSUE THREAD

**Issue by zacharyvincze** [sparksuite/simplemde-markdown-editor#402]
The mobile editing isn't very good for some reason.  The keyboard acts _very_ weird.

There is _no predictive text anymore_, and basically all of the functions that the iOS keyboard used to have.
- Switching to lowercase after a character has been typed.
- Adding a period after inputting two spaces
- No predictive text anymore
- Any other features that make text editing on iOS easier don't seem to work anymore.

I don't know if this is a problem with SimpleMDE or CodeMirror.  But I though it was something I should address.

I'm using the **iOS 9 keyboard**, just in case that information was needed.

I'm wondering if there is a fix for this, or if it's just a bug that has to be fixed.

**Comment by WesCossick** [comment]
This is an issue with CodeMirror, but it's due to the way CodeMirror handles allows content editing. It's probably unavoidable, but you're welcome to submit an issue with their repository.
