### ISSUE TITLE
How do I set other icons?

### ISSUE THREAD

**Issue by afuno** [sparksuite/simplemde-markdown-editor#403]
In the project I do not use FA icons. I have a local file with icons. Consequently, css classes are also others.

Disable autoload FA can this option:

```
autoDownloadFontAwesome
```

But how to replace all `fa fa-*` to other classes?

**Comment by afuno** [comment]
Not even just a class. I tried to manually edit button.
The problem is that your editor is strongly integrated FA icons.
Other icons simply can not normally penetrate.

**Comment by WesCossick** [comment]
The only way at the moment would be to fork the repository and update the CSS source file.
