### ISSUE TITLE
Bower packege files

### ISSUE THREAD

**Issue by jonatanklosko** [sparksuite/simplemde-markdown-editor#407]
In order to fix #326 the "main" files has been changed to these from `src` directory in the bower.json. 
Shouldn't the files be at least 'browserified'? The fact that they aren't causes problems in my Rails project.

**Comment by WesCossick** [comment]
See the spec: https://github.com/bower/spec/blob/master/json.md#main

> Entry-point files have module exports and may use module imports...so they can be used by build tools.
