### ISSUE TITLE
* symbol for bold is not working.

### ISSUE THREAD

**Issue by Josepdal** [sparksuite/simplemde-markdown-editor#413]
blockStyles: {
        bold: "*"
}

<img width="433" alt="d8c1a655037ca371c1b20e451a43edcf" src="https://cloud.githubusercontent.com/assets/11841883/17403521/7444904e-5a58-11e6-942b-4f887ec647f1.png">

How can I fix it?

**Comment by WesCossick** [comment]
The symbol for bold is `**bold**`

**Comment by Josepdal** [comment]
@WesCossick but i want to be \* instead of **

**Comment by WesCossick** [comment]
The `blockStyles` option only affects the text that is entered when you click a toolbar button. For example, using `_` instead of `*` for italics, since both are supported. It's not, however, designed to change the syntax entirely.

**Comment by faizan170** [comment]
> Can anyone help me with this?
