### ISSUE TITLE
Need more configuration when I need highlight code?

### ISSUE THREAD

**Issue by elantion** [sparksuite/simplemde-markdown-editor#415]
I have config like this:

```
simpleMDE = new SimpleMDE({
                element: document.getElementById('editor'),
                autoDownloadFontAwesome: false,
                spellChecker: false,
                placeholder: '使用Markdown开始编写你的文章...',
                renderingConfig: {
                    codeSyntaxHighlighting: true
                },
                tabSize: 4
            });
console.log(window.hljs); // it is there.
```

But when I'm editing my content, the code still not parsed highlight style. And I have already include highlight.js. What else should I need to do?

Thanks for your time.

**Comment by WesCossick** [comment]
These types of questions are better suited for StackOverflow.

**Comment by elantion** [comment]
But the document said only need to include highlight.js and set the codeSyntaxHighlighting: true. Dose the document incomplete?

**Comment by WesCossick** [comment]
You're going to need to set up a JSFiddle to replicate this error. Otherwise, we don't have enough information to help you.

**Comment by elantion** [comment]
I finally know that configuration is only working for preview. I though that is working for editing state too. Sorry.

**Comment by kindevil** [comment]
hello, I set the codeSyntaxHighlighting: true and include highlight.js, but the code still not parsed highlight style.Do you know why ?

**Comment by elantion** [comment]
Like I said: It only work for preview.

**Comment by kindevil** [comment]
I know, i'm work for preview too. finally i find the problem, highlight download from official website maybe some problems, i download a othor one fixed it.

**Comment by yaozhibo** [comment]
Hey man, does your preview work normally with highlightjs in adding className `.hljs` to `<pre>`?

**Comment by pdt590** [comment]
> I know, i'm work for preview too. finally i find the problem, highlight download from official website maybe some problems, i download a othor one fixed it.

@kindevil Can you share your solution?. I met same the problem. SimpleMDE cannot highlight properly when i use highlightjs
