### ISSUE TITLE
can't active side-to-side correctly if no fullscreen button in toolbar

### ISSUE THREAD

**Issue by truongngoctuan** [sparksuite/simplemde-markdown-editor#417]
if my toolbar only have toolbar option like this: `toolbar: ["side-by-side"]`, only the left side is showed

This is the error in the console:
`TypeError: toolbarButton is undefined`

the error is from these lines of code:

```
    // Update toolbar button
    var toolbarButton = editor.toolbarElements.fullscreen;

    if(!/active/.test(toolbarButton.className)) {
        toolbarButton.className += " active";
    } else {
        toolbarButton.className = toolbarButton.className.replace(/\s*active\s*/g, "");
    }
```

I am using Firefox and `simplemde v1.11.2`

**Comment by WesCossick** [comment]
Can you set up a JSFiddle and instructions so others can replicate this?

**Comment by CodyJamesCasey** [comment]
@WesCossick I'm also experiencing this issue.

https://jsfiddle.net/codyjamescasey/enghtgdf/
