### ISSUE TITLE
Trying to understand SimpleMDE and CodeMirror more

### ISSUE THREAD

**Issue by atsepkov** [sparksuite/simplemde-markdown-editor#418]
This is more of a question than a bug report so I apologize if I asked this in a wrong place.

SimpleMDE introduces a number of features from GitHub-flavored Markdown (GFM) in CodeMirror. However, syntax highlighting in edit mode (not just preview mode) seems to be missing. Moreover, I can't seem to reenable it by including additional plugins from CodeMirror as they suggest (probably because CodeMirror class isn't exposed by SimpleMDE).

In addition to syntax highlighting, I'd like to add closebrackets plugin to my instance of SimpleMDE so writing code blocks becomes a little easier. Based on my use cases, I had a few questions:
- How come not all GFM features are supported? Is the GFM mode in SimpleMDE implemented differently than the vanilla gfm.js in CodeMirror or is the problem simply that SimpleMDE doesn't load the additional syntax highlighter plugins that gfm.js relies on?
- If it's the later, can I load/apply them without modifying SimpleMDE code? And if not, is it possible to have something like an init flag in SimpleMDE (i.e. `codeBlockModes: ['javascript', 'python', 'css']`) to have SimpleMDE attempt to load the relevant `lang.js` file user links on the page)?
- Similarly to number 2, is it possible to load the closedbrackets plugin?

Thank you

**Comment by brondsem** [comment]
You can still access the underlying codemirror configuration.  For example, to implement the configuration mentioned here https://github.com/codemirror/CodeMirror/issues/1576#issuecomment-19146595 I did:

``` js
var editor = new SimpleMDE({ ... });
editor.codemirror.options.extraKeys.Home = "goLineLeft";
editor.codemirror.options.extraKeys.End = "goLineRight";
```

And SimpleMDE's `parsingConfig` option gets passed through, so you can set other GFM options, e.g. `taskLists: false` if needed.

**Comment by atsepkov** [comment]
Vanilla CodeMirror seems to be creating `CodeMirror` object in global scope, which many of the plugins piggyback on by appending functionality to it. SimpleMDE seems to hide the object in its own scope, so when I include one of these extra libraries on the page I get the following error:

> Uncaught ReferenceError: CodeMirror is not defined

It looks like XML/HTML mode does work out of the box, which is consistent with what I'd expect from the source: https://github.com/NextStepWebs/simplemde-markdown-editor/blob/master/src/js/simplemde.js . It looks like I would have to modify the source, however, to include additional languages unless there is some option to expose CodeMirror object the same way that I'm missing?

**Comment by brondsem** [comment]
Sorry I'm running an older version of SimpleMDE still, so it might be different.

The "CodeMirror is not defined" has been a recent error in several bug reports.  1.11.2 has it fixed. https://github.com/NextStepWebs/simplemde-markdown-editor/releases/tag/1.11.2

**Comment by atsepkov** [comment]
I'm using CodeMirror from the CDN: https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js (which is 1.11.2 as well). I looked through a few of the "CodeMirror not defined" bug reports, it looks like their issue occurred for modules that should already be embedded in SimpleMDE itself (i.e. spellchecker). In my case this isn't a module that's pre-bundled with SimpleMDE, so it doesn't look like a bug in SimpleMDE, just that I may not be able to include the extra libs without rebuilding simplemde.min.js.

**Comment by WesCossick** [comment]
So you're saying that some of CodeMirror's plugins are assuming that the CodeMirror object has global scope? If so, then that's an issue with the plugins and not SimpleMDE.

**Comment by atsepkov** [comment]
Unless I'm misreading the source, every plugin (including the official ones) seems to be making that assumption, here are some examples:

https://github.com/codemirror/CodeMirror/blob/master/mode/javascript/javascript.js
https://github.com/codemirror/CodeMirror/blob/master/mode/clike/clike.js
https://github.com/codemirror/CodeMirror/blob/master/mode/xml/xml.js
https://github.com/codemirror/CodeMirror/blob/master/addon/edit/closebrackets.js

I'm referring to this line (typically line 10-12 in each plugin):

```
mod(CodeMirror);
```

which seems to be the way to bootstrap plugins in browser environment.

**Comment by WesCossick** [comment]
Looks like the source files are designed to be built into a packaged script. If they're just included using script tags, then they'll assume they're being used globally. You may want to fork SimpleMDE and build in any plugins needed yourself.
