### ISSUE TITLE
Error in testing with jasmine

### ISSUE THREAD

**Issue by janis91** [sparksuite/simplemde-markdown-editor#419]
Hi, currently I am working on an app which should include the simplemde. My intention is to test my custom js code in order to make sure everything is fine. But if I try to run my karma config with jasmine and include the simplemde.js (debug version), I get this error:

```
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  TypeError: undefined is not an object (evaluating 'textarea.value')
  at js/simplemde.min.js:8237
```

Some functions of my app require simplemde and I want to get my tests working for them, so I need simplemde.

Maybe you know what is going wrong here?

**Comment by WesCossick** [comment]
This may be a question that's better suited for StackOverflow. Be sure to provide more code samples and explanation than you've provided here.
