### ISSUE TITLE
Support for preset images

### ISSUE THREAD

**Issue by djpate** [sparksuite/simplemde-markdown-editor#421]
I would love for it to have support for a list of available images.

The custom toolbar is pretty close but It would require some sort of sub options under the main toolbar icon. 

would be really useful for CMS.

Thanks for the great work.

**Comment by WesCossick** [comment]
Not sure if I fully understand this use case...

**Comment by Deaygo** [comment]
@WesCossick Having the ability have a callback function, that would allow one to show a modal with images that exist on the server which can be selected from.

**Comment by WesCossick** [comment]
That seems quite a bit too specific of a use case to build into SimpleMDE. You can use the options to create your own toolbar button with your own JavaScript code, though.
