### ISSUE TITLE
Allow users to edit preview

### ISSUE THREAD

**Issue by ericroberts** [sparksuite/simplemde-markdown-editor#422]
So far I love pretty much everything I've seen about this editor, but I think it would be great if there was an option to allow editing the preview (and to hide the markdown). As far as I can tell this doesn't exist, but it would it be something that would be accepted as a contribution?

**Comment by ericroberts** [comment]
I discovered that if I use css to hide the class `cm-formatting`, it displays as I want, and is still editable. However there are some issues with highlighting and editing with the formatting classes hidden. Do you know of any reason why this would cause an issue?

**Comment by WesCossick** [comment]
Duplicate of #319, #302, #281, and #232
