### ISSUE TITLE
Previewing contents of editor into a separate div

### ISSUE THREAD

**Issue by audigex** [sparksuite/simplemde-markdown-editor#423]
Apologies if I'm missing something obvious in the API or documentation!

I'm looking to do a "live preview", similar to how StackOverflow does - ie a live preview of the editor content into a div, similar to the side by side mode but filling a separate div/object

Is there a simple way to do this? I'm envisaging an option like

```
livePreview: "previewDivID",
```

Alternately, is there a version of `simpleMDE.value()` that gives the parsed contents? eg `simpleMDE.parsedValue()` that I could use within `simplemde.codemirror.on("change"....`

eg

```
// Preview markdown changes
simplemde.codemirror.on("change", function () {
    // Fill div contents 
    document.getElementByID("customPreview").innerHTML = simpleMDE.parsedValue();
});
```

Thanks

**Comment by audigex** [comment]
I've now discovered the `simpleMDE.markdown()` method, which seems to answer the latter part of my query:

I can now do something like

```
simplemde.codemirror.on("change", function () {
    $("#preview").html( simplemde.markdown( simplemde.value() ) );
});
```

I'll leave this open as I'm still curious as to the first part of my query

**Comment by WesCossick** [comment]
There is no built-in way to achieve this. It shouldn't take more than few lines of your own application logic code to do this, though.
