### ISSUE TITLE
SimpleMDE loads a font from a CDN

### ISSUE THREAD

**Issue by sternenseemann** [sparksuite/simplemde-markdown-editor#424]
Please make this at least configurable. Loading external resources via a CDN undermines the user's privacy which is something specifically people hosting the JavaScript themselves don't want.

**Comment by bengotow** [comment]
I believe this is configurable via `autoDownloadFontAwesome` https://github.com/NextStepWebs/simplemde-markdown-editor#configuration

**Comment by sternenseemann** [comment]
What does “download” refer to in this context? Using the CDN? Or is it a build-time flag?

**Comment by danabrey** [comment]
From the docs: 

> autoDownloadFontAwesome: If set to true, force downloads Font Awesome (used for icons). If set to false, prevents downloading. Defaults to undefined, which will intelligently check whether Font Awesome has already been included, then download accordingly.

"Download" refers to downloading FontAwesome from a CDN.

If the option is set to false, then FontAwesome won't be downloaded from a CDN, so you're able to download FontAwesome from a different location of your choice.

To see how the option is implemented, you might be interested in [this bit of the source](https://github.com/NextStepWebs/simplemde-markdown-editor/blob/master/src/js/simplemde.js#L1273).

**Comment by WesCossick** [comment]
@danabrey is 100% correct.

**Comment by maulayyacyber** [comment]
how to disconnect load font awesome from cdn ?
