### ISSUE TITLE
How to modifiy the drawImage function

### ISSUE THREAD

**Issue by babeuloula** [sparksuite/simplemde-markdown-editor#426]
Hello, 

I need to modify the drawImage function to show a popup with the uploaded images on the server and choosing an existing image.
Then I choose the picture, I need to insert the good URL into `![]()`.

I made this into toolbar option array : 

``` javascript
{
    name: "imageCustom",
    action: function drawImageCustom(editor){
        // Launch a bootstrap modal with the picture
        ....

        // But how I can insert the code ![](My_URL) into SimpleMDE ?
    },
    className: "fa fa-picture-o",
    title: "Insert Image"
}
```

Thanks for your replies.
Regards

**Comment by babeuloula** [comment]
``` javascript
var cm = editor.codemirror;
cm.replaceSelection("![](My_URL)");
```

**Comment by Avcajaraville** [comment]
@babeuloula Thanks ! You saved me some deeper code read :)
