### ISSUE TITLE
Disable syncroll on preview side

### ISSUE THREAD

**Issue by babeuloula** [sparksuite/simplemde-markdown-editor#427]
Hello, 

When I use the preview side by side, sometime my markdown is not aligned with the preview : 
![image](https://cloud.githubusercontent.com/assets/4849233/18162865/781948ea-7038-11e6-84b0-14c02e86b6a2.png)

It's better if when we scroll on the preview side, the syncscroll does not launch. But if we scroll on the markdown side, launch the syncscroll.

Thanks

**Comment by WesCossick** [comment]
This is just a side effect of how some content will have varying heights between the edit mode and the preview mode. Disabling synchronized scrolling on one side would only make the issue worse, because the scrolling would become misaligned.

**Comment by TangentFoxy** [comment]
Perhaps make it a configurable option? I can see times where it might be handy to be able to look at things not locked in this manor.
