### ISSUE TITLE
Fullscreen mode is broken when multiple editors are present on the page

### ISSUE THREAD

**Issue by jetmind** [sparksuite/simplemde-markdown-editor#43]
E.g. https://jsfiddle.net/ehmt3yLw/

I believe this is due to [these](https://github.com/NextStepWebs/simplemde-markdown-editor/blob/fc6fd130255956f936cbd51452b5edd74c4c3a37/source%20files/codemirror/fullscreen.js#L30) [lines](https://github.com/NextStepWebs/simplemde-markdown-editor/blob/fc6fd130255956f936cbd51452b5edd74c4c3a37/source%20files/codemirror/fullscreen.js#L41), but am not sure how to fix it right away.

The first thing that pops into my mind is:

``` javascript
var toolbar = wrap.parentElement.getElementsByClassName("editor-toolbar")[0];
toolbar.className += " fullscreen";
```

but this won't work if both editors are in the same parent, like in jsfiddle above.

**Comment by jetmind** [comment]
I've just realised that `wrap.previousSibling` should probably work

**Comment by WesCossick** [comment]
Thanks, great catch! I've fixed this and will be releasing 1.5.1 soon.

**Comment by jetmind** [comment]
Thanks! You're fast ;)

We're using your editor for http://allura.apache.org, largest deployment of which is http://sourceforge.net, so it is pretty intensively tested by users now. It is great so far! Though, I guess you should expect some more bug reports and/or feature requests soon ;)

**Comment by WesCossick** [comment]
Wow, that's awesome! I'm building it into a new version of some software that's heavily used, so I'm glad that it's been well tested. This is the main reason why I decided to open source it. Just let me know if you find any other bugs or have any other feature requests.
