### ISSUE TITLE
Line breaks and list detection

### ISSUE THREAD

**Issue by zirafa** [sparksuite/simplemde-markdown-editor#430]
When rendering a list with a preceding line above it:

```
Listing some items
- item 1
- item 2
```

According to the original markdown spec and [Dingus](http://daringfireball.net/projects/markdown/dingus), this should render as a single paragraph with no list elements:

```
<p>Listing some items
- item 1
- item 2</p>
```

However Simplemde always renders this as a paragraph followed by a ul list:

```
<p>Listing some items</p>
<ul>
  <li>item 1</li>
  <li>item 2</li>
</ul>
```

I actually really like the way Simplemde handles this by default, but it does create some consistency problems when using Simplemde on the frontend mixed with a strict markdown parser on the backend. 

Is there a "strict" mode that would render the preview the according to the Markdown spec / Dingus?

**Comment by zirafa** [comment]
I see that [Marked](https://github.com/chjj/marked) is being used for preview rendering...is it possible to just directly pass options to it rather than having [separate renderingConfig options](https://github.com/NextStepWebs/simplemde-markdown-editor/blob/master/src/js/simplemde.js#L1395)? I suspect the list behavior is controlled by Marked's smartLists: true option and it'd be nice to set those options directly.

**Comment by TangentFoxy** [comment]
@zirafa SimpleMDE uses Github Flavored Markdown. The underlying Marked can have GFM processing disabled, look at the ReadMe. Whether you do this yourself or it becomes a supported feature of SimpleMDE I don't know. I just switched to using Marked myself, but I support this being an option.

**Comment by zirafa** [comment]
I found a recent PR #366 on the development branch allowing markedOptions to be preset, which would resolve this issue.

**Comment by WesCossick** [comment]
Take a look at the `singleLineBreaks` option to disable this particular behavior of GFM.

**Comment by zirafa** [comment]
The singleLineBreaks option doesn't seem to help, it appears gfm has to be set to false for Marked to get the desired behavior. Might be a bug with Marked, not sure.

**Comment by martineso** [comment]
I was having troubles with this as well. As mentioned by @zirafa 

> The singleLineBreaks option doesn't seem to help, it appears gfm has to be set to false for Marked to get the desired behavior. Might be a bug with Marked, not sure.

the singleLineBreaks option does not work. 
The workaround I used is to directly edit the SimpleMDE source code. 
```
SimpleMDE.prototype.markdown = function(text) {
	if(marked) {
		// Initialize
		var markedOptions = {}; <<<
.....
// Replace with
>>>
var markedOptions = {
  gfm: false,
  pedantic: true,
}
```
This is will use the original markdown.pl spec as mentioned in the [*marked.js* documentation.](https://marked.js.org/#/USING_ADVANCED.md)

It may be useful to add an option to directly overwrite the markedOptions object in future releases.
