### ISSUE TITLE
Cross site scripting [self xss] on simplemde-markdown-editor

### ISSUE THREAD

**Issue by raminfp** [sparksuite/simplemde-markdown-editor#435]
Hi,

there is vulnerability XSS on simplemde editor , 

steps : 

1 - Go to https://simplemde.com/
2 - copy this `'><img src=x onerror=alert(1);>`  or `<img src=x onerror=alert`Hello!`>` or `<b onclick=alert(1)>click me!` and etc
3 - paste on [simplemde-markdown-editor](https://simplemde.com/) 
4 - click to preview 
5 - you see execute javascript code,

Thanks,
Ramin

**Comment by TangentFoxy** [comment]
Correct me if I'm wrong, but this is due to Markdown allowing HTML to be used within it, and the problem is just that their demo doesn't disable that. It's not an inherent error/danger in SimpleMDE itself?

**Comment by RaminFP** [comment]
i don't know on SimpleMDE safe mode is enable or no in [README](https://github.com/NextStepWebs/simplemde-markdown-editor/blob/master/README.md), if you have test with `<script>alert(1)</script>` you will filter javascript tag in SimpleMDE, on mardown html tag should filter, like `img , svg and ...`

**Comment by WesCossick** [comment]
This is due to Markdown allowing HTML to be used alongside the Markdown syntax. SimpleMDE makes no effort to filter this client side. Your own application code should worry about handling these types of attacks.

**Comment by davidcalhoun** [comment]
I would be super nice to add this as a recommendation in the docs for `previewRender`.
