### ISSUE TITLE
Preview Mode by default

### ISSUE THREAD

**Issue by andrelgarcia** [sparksuite/simplemde-markdown-editor#436]
Is there a way to load the editor already on preview mode?
I'm using it on a form edit page.

Thanks!

**Comment by CodyJamesCasey** [comment]
@andrelgarcia you can do something like

```
const simplemde = new SimpleMDE(options);

simplemde.togglePreview();
```

**Comment by andrelgarcia** [comment]
Thanks, man. 
And also, sorry. I finally found it on the documentation.

**Comment by CodyJamesCasey** [comment]
no worries!

**Comment by matimiodosky** [comment]
> @andrelgarcia you can do something like
> 
> ```
> const simplemde = new SimpleMDE(options);
> 
> simplemde.togglePreview();
> ```

Is this working? Not for me 😢
