### ISSUE TITLE
Catch full screen event?

### ISSUE THREAD

**Issue by hukadev** [sparksuite/simplemde-markdown-editor#438]
Hi guys,

Can you show me how to catch "full screen" event? I have a problem when use SME with Drawer (Material Design Lite). See my attach file please.

Regard,
Huka.

![smde.png](http://2.pik.vn/2016a85ee375-ec9b-4e0b-80d3-735d2a8c4e4a.png)

**Comment by CodyJamesCasey** [comment]
@hukacode 
You can explicitly set your toolbar items and wrap the SimpleMDE.toggleFullScreen function call with your own logic.

```
var simplemde = new SimpleMDE({
    toolbar: [{
            name: "fullscreen",
            action: handleToggleFullscreen,
            className: "fa fa-arrows-alt no-disable no-mobile",
            title: "Toggle Fullscreen",
        },
        ...
    ],
    ...
});

const handleToggleFullscreen = () => {
  //perform whatever logic you want
  simplemde.toggleFullScreen()
}
```

**Comment by hukadev** [comment]
Hi @CodyJamesCasey ,

It's worked like a magic. Thank you so much!

**Comment by CodyJamesCasey** [comment]
![](https://media.giphy.com/media/2t9sDPrlvFpdK/giphy.gif)

**Comment by ngyikp** [comment]
The custom code won't fire if the user exits full screen by pressing the Esc key though. Is there no other alternate way?

**Comment by ngyikp** [comment]
Ended up just doing a monkey-patch on CodeMirror's `setOption`:

``` js
const oldEditorSetOption = editor.codemirror.setOption;
editor.codemirror.setOption = function(option, value) {
    oldEditorSetOption.apply(this, arguments);

    if (option === 'fullScreen') {
        // your code...
    }
};
```

**Comment by xcatliu** [comment]
@CodyJamesCasey

This won't work if user press [keyboard shortcuts](https://github.com/NextStepWebs/simplemde-markdown-editor#keyboard-shortcuts) `F11` to toggle fullscreen

**Comment by HermannBjorgvin** [comment]
@CodyJamesCasey used this for a custom image upload modal, thanks a bunch!
