### ISSUE TITLE
No underline ?

### ISSUE THREAD

**Issue by zecompadre** [sparksuite/simplemde-markdown-editor#439]
no option for underline text ?

tks

**Comment by danabrey** [comment]
SimpleMDE uses [GitHub flavoured Markdown](https://help.github.com/articles/basic-writing-and-formatting-syntax), which (along with [regular Markdown](https://daringfireball.net/projects/markdown/syntax)) has no support for underlining text.

**Comment by zecompadre** [comment]
ok ! tks
