### ISSUE TITLE
Spell Check locales

### ISSUE THREAD

**Issue by roccogalluzzo** [sparksuite/simplemde-markdown-editor#440]
Hi,

there is a way to specify a lang for the editor spellcheck?

**Comment by WesCossick** [comment]
Not yet. For this to function, it'd need to be implemented first in CodeMirror Spell Checker: https://github.com/NextStepWebs/codemirror-spell-checker/issues/16

**Comment by andycansdale** [comment]
Looks like this will be added any day now: https://github.com/sparksuite/codemirror-spell-checker/pull/39
