### ISSUE TITLE
CSS red spots

### ISSUE THREAD

**Issue by sabinem** [sparksuite/simplemde-markdown-editor#441]
Thanks you very much. This is a splendid Editor and I love it. When I work with it, I sometimes get colored spots in my text while writing. I am not sure what that is and how to fix it: some sort of CSS overlay. Has anyone an idea for me? I attach a screenshot. Thanks in advance for your help.
<img width="587" alt="bildschirmfoto 2016-10-07 um 11 23 06" src="https://cloud.githubusercontent.com/assets/5292683/19185204/e3f5a342-8c80-11e6-89a9-50b8507bcb66.png">

**Comment by Hum4n01d** [comment]
I believe that's the spell checking. You should be able to turn that off 

(disclaimer: I'm not the creator of this project but I like the editor)

**Comment by sabinem** [comment]
Thank you so much, yes your are right it is the spell checker. Great! I might even keep it in that case.

**Comment by Hum4n01d** [comment]
No problem :)
