### ISSUE TITLE
Alternative Headers

### ISSUE THREAD

**Issue by Henni** [sparksuite/simplemde-markdown-editor#450]
Currently the following input is rendered incorrectly:

``` markdown
test
=====
more content.....
```

![image](https://cloud.githubusercontent.com/assets/1267827/19703466/36470f96-9b04-11e6-9c43-fa69bf92d6f1.png)

Instead the word `test` should also be rendered as a heading.
The same problem occurs with `-----` which should render the line above as h2.

**Comment by WesCossick** [comment]
Duplicate of https://github.com/NextStepWebs/simplemde-markdown-editor/issues/412
