### ISSUE TITLE
I can not revert to HTML

### ISSUE THREAD

**Issue by thaifast** [sparksuite/simplemde-markdown-editor#452]
I can not revert to HTML
For example, `<?php echo "** BBCODE **";?>`
Results not displayed in bold.

**Comment by FabianKoestring** [comment]
Github doesnt convert `** BBCODE **` to bold text too. It must be `**BBCODE**` or am i wrong?

**Comment by TangentFoxy** [comment]
@FabianKoestring Indeed, asterisks need to be touching the word(s) they are bolding.

@thaifast What exactly are you saying though? Your example doesn't make sense, as that would _literally_ just print `** BBCODE **` into part of a webpage..
