### ISSUE TITLE
Loading autosaved value manually

### ISSUE THREAD

**Issue by sebastiaanluca** [sparksuite/simplemde-markdown-editor#458]
Upon loading a page that has a SimpleMDE editor with autosave enabled, it automatically sets that saved data as value of the textarea. Is there a way to keep autosave enabled for that unique field, but prevent the auto-assign from happening?

The goal would be to allow the user to click a button to manually load the saved contents into the textarea/simplemde editor, i.e. loading the page with the original contents, but providing a "load autosaved data"-button to the user. Additionally a reset button too. Regarding this, does the editor provide a method to retrieve the saved data? I only found `simplemde.clearAutosavedValue();` in the readme.

**Comment by WesCossick** [comment]
You may want to look into developing your own autosave functionality in this case. SimpleMDE's implementation is rather simple, it wouldn't be hard to recreate and modify.

**Comment by sebastiaanluca** [comment]
JavaScript isn't my main dev language, so that's not an option for me I'm afraid. Is there a simple way to check if saved content has been loaded instead of the value that was set on the textarea?

**Comment by WesCossick** [comment]
There is not, no.

**Comment by sharifanani** [comment]
Is there a way to discard the autosaved value? The use case seems common enough:

A user edits, but then decides to just scrap everything and revert to the original value without submitting the form
