### ISSUE TITLE
Numbered list on given text

### ISSUE THREAD

**Issue by FabianKoestring** [sparksuite/simplemde-markdown-editor#459]
If you type some text ...

```console
dadasdsa
dasfdgdf
hjgjgjghj
```

and then mark the text and klick the numbered list button you will get..

```console
1. dadasdsa
1. dasfdgdf
1. hjgjgjghj
```

**Comment by blfpd** [comment]
This is perfectly correct Markdown.
Converted to HTML it will get you the right numbering.

From [Markdown author](http://daringfireball.net/projects/markdown/syntax):

> Ordered lists use numbers followed by periods:

```
1.  Bird
2.  McHale
3.  Parish
```

> It’s important to note that the actual numbers you use to mark the list have no effect on the HTML output Markdown produces. The HTML Markdown produces from the above list is:

```
<ol>
<li>Bird</li>
<li>McHale</li>
<li>Parish</li>
</ol>
```

> If you instead wrote the list in Markdown like this:

```
1.  Bird
1.  McHale
1.  Parish
```

**Comment by WesCossick** [comment]
There's currently a broken PR pending for this, as it may confuse some users. It's here: #374. If you'd like to submit a working PR, it would help move this change along.
