### ISSUE TITLE
Emphasis styling still renders even with spaces around * and _

### ISSUE THREAD

**Issue by shawndibble** [sparksuite/simplemde-markdown-editor#465]
In normal markdown, if you have `**Word**`, then it should render as bold, however ** Word ** should render with the stars showing (normal weight). Same goes for italics. If there are spaces, it should not render as bold. You can even see how this is suppose to work in even github's interface.

That being said, is there a way to make it so that when I am editing/previewing and my user does something like *Some text *, then simplemde doesn't render it as bold unless the user removes the space at the end?

I ask because I am using simplemde for things that are emailed out and if the user isn't aware of this quirk, they will think that bold and italics will render properly when in reality it will just show the *s and _s.

**Comment by WesCossick** [comment]
The rendering during editing is handled by **CodeMirror**, and the rendering during previewing is handled by **marked**. You'll need to submit issues with both of those projects to see the change incorporated into SimpleMDE.
