### ISSUE TITLE
Want to render HTML as HTML

### ISSUE THREAD

**Issue by ghost** [sparksuite/simplemde-markdown-editor#475]
I think there should be an option to preserve HTML in the editor, without breaking it down into editable text. E.g. editing the markdown

    Inline **math equations** go in like so: <span class="math inline mq-editable-field mq-math-mode"><span class="mq-textarea"></span></span>
<span class="mq-root-block" mathquill-block-id="1">ω<span class="mq-binary-operator" mathquill-command-id="4">=</span>dϕ<span mathquill-command-id="10">/</span>dt</span>.

would show this

![](http://i.cubeupload.com/uUh13C.png)

instead of what it would currently show which is this:

![](http://i.cubeupload.com/yEBZ3c.png)

**Comment by WesCossick** [comment]
SimpleMDE's composition window supports plain text. It cannot render HTML and also support typing in plain text.

**Comment by ghost** [comment]
Actually, it can. How does it render the formatting then? Nothing about it is plain text.
