### ISSUE TITLE
Cannot read property 'getAttribute' of undefined

### ISSUE THREAD

**Issue by andy4545** [sparksuite/simplemde-markdown-editor#478]
I get this error  in chrome console. 
```
Uncaught TypeError: Cannot read property 'getAttribute' of undefined
    at B.render (https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js:15:4470)
    at new B (https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js:14:28861)
```
It relates to this line 
`placeholder: options.placeholder || el.getAttribute("placeholder") || "",  `

I have tested it with a bare-bones html file - and i still get the issue eg - using this code
```
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
    <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
</head>

<body>
<script>
    var simplemde = new SimpleMDE();
</script>
</body>
```

**Comment by howsun** [comment]
**No textarea element on the page.**
> Configuration:
> element: The DOM element for the textarea to use. Defaults to the first textarea on the page.
