### ISSUE TITLE
Whitespace gets prepended on load/display

### ISSUE THREAD

**Issue by midwire** [sparksuite/simplemde-markdown-editor#480]
I love the functionality of this editor.  However, whenever it loads some text it inserts spaces.

![celebrity_boycott_list](https://cloud.githubusercontent.com/assets/178386/21032554/c0cd1fa6-bd6f-11e6-9ff9-4d1e1728dd65.jpg)

This is what the string looks like before it is loaded the first time:

> "# Intro\nThis text should not be indented. It does not have any spaces in front of it but it shows up with 16 spaces every time it gets loaded.\n\nThen, if I save this text and load it again in the editor it gets 16 more spaces prepended."

I can't find a configuration setting to address this issue. What am I doing wrong?

**Comment by technodrome** [comment]
Just by chance, are you using this inside a Rails app with HAML?

I tried to fix this with: `tabSize: 0` but it broke randomly. 
Then I tried HAML whitespace preservation tag - tilde. That seems to work for now.

HAML documentation says: 
> Sometimes you don’t want Haml to indent all your text. Tags like pre and textarea are whitespace-sensitive; indenting the text makes them render wrong. Literal textarea and pre tags automatically preserve content given through =. Dynamically-generated textareas and pres can’t be preserved automatically, and so should be passed through `Haml::Helpers#find_and_preserve` or the `~` command, which has the same effect.

http://haml.info/docs/yardoc/file.REFERENCE.html#whitespace_preservation
http://haml.info/docs/yardoc/file.REFERENCE.html#tilde

**Comment by connorphill** [comment]
I receive the same issue with NodeJS and Handlebars. The source code shows non-character whitespace within the `<textarea>` tags and within the developer console, `<pre class=" CodeMirror-line">` for both line breaks and text, which is causing the markdown to appear as code rather than the markdown formatting applied to the string. Any way to prevent this behavior with the Simplemde options?

**Comment by midwire** [comment]
> Just by chance, are you using this inside a Rails app with HAML?

Yep. That was the problem. The `find_and_preserve` operator `~` worked perfectly. Thanks @technodrome!

**Comment by ltdev22** [comment]
I have the same issue, I have also posted it [here](http://stackoverflow.com/questions/42923696/rails-simplemde-content-displays-indented). So if I understand correct I need to replace the textarea that has simplemde ie = f.input with ~ f.input, correct?

**Comment by midwire** [comment]
@Lykos22 yes. that worked for me.
