### ISSUE TITLE
React app, not able to rerender, refresh, reload content

### ISSUE THREAD

**Issue by gazpachu** [sparksuite/simplemde-markdown-editor#482]
I've been reading as much as I can and tried `refresh()`, `render()`, `forceSync`, etc, with no luck.

It seems the library doesn't include these methods.

My textarea is correctly updated using React local state, but it's imposible for me to update the editor from the textarea

**Comment by DavidRayPatterson** [comment]
[react-simplemde-editor](https://github.com/benrlodge/react-simplemde-editor) is a react component wrapper for simplemde which might solve your issues.

**Comment by gazpachu** [comment]
@DavidRayPatterson Thanks!
