### ISSUE TITLE
"Please fill out this field."

### ISSUE THREAD

**Issue by paulcunnane** [sparksuite/simplemde-markdown-editor#484]
If the underlying textarea has the "required" attribute, it's impossible to submit the form in recent Chrome versions that do client-side form validation. The browser attempts to add a "Please fill out this field" balloon to the textarea, but fails, because it's not visible.

I know it's possible to work around this by telling Chrome not to validate the form; I have other workarounds I can use. The issue remains, however.

**Comment by WesCossick** [comment]
Duplicate of https://github.com/NextStepWebs/simplemde-markdown-editor/issues/324
