### ISSUE TITLE
Handle jekyll YAML frontmatter

### ISSUE THREAD

**Issue by Floppy** [sparksuite/simplemde-markdown-editor#487]
Thanks for SimpleMDE, it's amazing! I'm using it to edit pages in a Jekyll site, and each one has [YAML frontmatter](https://jekyllrb.com/docs/frontmatter/). Currently the formatting goes a bit odd, as shown in the image below:

<img width="234" alt="screen shot 2016-12-16 at 22 39 56" src="https://cloud.githubusercontent.com/assets/3565/21280896/ba6e1e18-c3e0-11e6-9c16-d39147696560.png">

Formatting in preview is even worse, it shows as a heading, which makes sense with the following underlines of course.

It would be great if the editor had an option to handle frontmatter, and either style it sensibly, or hide it away completely.

**Comment by WesCossick** [comment]
At this time, SimpleMDE is focused on Markdown syntax only (hence the "MD" in the name). For editing other markup languages, it's probably best to create a fork of the project and modify the parsing engines.

**Comment by Floppy** [comment]
Reading back, I see I didn't actually explain the use case properly. Jekyll uses markdown pages with short YAML metadata sections at the start (pictured), so while it's not pure markdown, the bulk of the page is.

However, I understand that you're not building a Jekyll editor, just a Markdown one. I'll see if I can do something in a fork to ignore the metadata, and will contribute back if it's useful more widely.
