### ISSUE TITLE
Render HTML within editor

### ISSUE THREAD

**Issue by ghost** [sparksuite/simplemde-markdown-editor#488]
I think there should be an option to preserve HTML in the editor, without breaking it down into editable text. E.g. editing the markdown

    Inline **math equations** go in like so: <span class="math inline mq-editable-field mq-math-mode"><span class="mq-textarea"></span></span>
<span class="mq-root-block" mathquill-block-id="1">ω<span class="mq-binary-operator" mathquill-command-id="4">=</span>dϕ<span mathquill-command-id="10">/</span>dt</span>.

would show this

![](http://i.cubeupload.com/uUh13C.png)

instead of what it would currently show which is this:

![](http://i.cubeupload.com/yEBZ3c.png)

**Comment by ghost** [comment]
This is very possible, so don't just close it.

**Comment by WesCossick** [comment]
Duplicate of https://github.com/NextStepWebs/simplemde-markdown-editor/issues/475.

I'm not sure if you have a complete grasp of Markdown, the syntax that SimpleMDE allows you to write in. Markdown is a plaintext language when you're writing it, and then when you render it, it turns into HTML. By it's nature, Markdown allows HTML code to be written in it, but again, you're writing in plaintext, then rendering to HTML.
