### ISSUE TITLE
Cursor in textarea shows Â

### ISSUE THREAD

**Issue by brandonlou** [sparksuite/simplemde-markdown-editor#489]
The cursor in the textarea looks like a normal cursor but with Â to the right of it. Currently happening in Chrome. It also leaves a trace when I enter a new line.
<img width="275" alt="screen shot 2016-12-22 at 2 30 31 pm" src="https://cloud.githubusercontent.com/assets/14984696/21442547/575302cc-c853-11e6-855c-6d1551c70c46.png">

**Comment by docluv** [comment]
I am having the same issue on the deployed site. Works fine on localhost.

**Comment by adelphes** [comment]
I am having the same issue on a localhost site.
The problem occurs because the page encoding is incorrect or not specified.
See https://github.com/codemirror/CodeMirror/issues/2276 for more explanation.
