### ISSUE TITLE
Is it required to set `box-sizing: border-box;` to `body`?

### ISSUE THREAD

**Issue by xcatliu** [sparksuite/simplemde-markdown-editor#493]
If I didn't set `box-sizing: border-box` to `body`, the side-by-side view might has some small issue:

![image](https://cloud.githubusercontent.com/assets/5453359/21562413/bb7c4450-ceb3-11e6-8ed7-e2492d538b11.png)

The `width: 50%` for `.CodeMirror-sided` and `.editor-preview-side` didn't get the correct width.
It may cause some text rendered outside of it's container.

Considering add a wrapper to `.CodeMirror-sided` and `.editor-preview-side` and set `box-sizing: border-box` to it?

**Comment by WesCossick** [comment]
I'll look into this...
