### ISSUE TITLE
Markdown Extra

### ISSUE THREAD

**Issue by mikerockett** [sparksuite/simplemde-markdown-editor#494]
I know this package is meant to be simple (as implied), but would it be possible to add Markdown Extra features? For clarity, these are:

1. Markdown inside HTML blocks
2. Elements with id/class attribute
3. Fenced code blocks
4. Tables
5. Definition lists
6. Footnotes
7. Abbreviations

I use some of these features all the time. For me, the most important features would be features 2, 5, 6, and 7.

Other than that, this is an excellent editor - only good one I can find.

**Comment by WesCossick** [comment]
Glad you like the editor. You can use your own preview rendering function for the preview. But while editing, you'd need to see if CodeMirror supported a parser with the extra features. This most likely will not be developed into SimpleMDE natively, though.

**Comment by MarcGab** [comment]
@mikerockett by markdown extra features for tables do you mean WYSIWYG Table rendering?

Do you know an editor that supports ["rich table editing" like atlassian confluence](https://www.youtube.com/watch?v=sdphqD0xutM)?
