### ISSUE TITLE
Add themes support

### ISSUE THREAD

**Issue by xcatliu** [sparksuite/simplemde-markdown-editor#498]
Hi,

I really love SimpleMDE, it's an awesome project ❤
But I got hurt when I want to customize my own theme.

So I spent some time to build **a theme system for SimpleMDE**, please help to review it!

If you think this is useful, is it possible to **add a link in this project** to guide people creating their own themes?

---

### [SimpleMDE Theme Base](https://github.com/xcatliu/simplemde-theme-base)
This is the base theme, every theme should based on it.

- [GitHub Repo](https://github.com/xcatliu/simplemde-theme-base)
- [Demo](http://simplemde-theme-base.mazimd.com/)

![Screenshot of SimpleMDE Theme Base](https://raw.githubusercontent.com/xcatliu/simplemde-theme-base/master/docs/screenshot.png)

### [SimpleMDE Theme Dark](https://github.com/xcatliu/simplemde-theme-dark)

This is a dark theme, as an example of creating new themes.

- [GitHub Repo](https://github.com/xcatliu/simplemde-theme-dark)
- [Demo](http://simplemde-theme-dark.mazimd.com/)

![Screenshot of SimpleMDE Theme Dark](https://raw.githubusercontent.com/xcatliu/simplemde-theme-dark/master/docs/screenshot.png)

### [List of Themes](https://github.com/xcatliu/simplemde-theme-base/wiki/List-of-themes)

Everyone can edit this page to add their themes.

### [How to create your theme](https://github.com/xcatliu/simplemde-theme-base#create-your-theme)

Creating a theme is super easy, there are only a few colors need to be changed:

```scss
//
//
// An example for dark theme
//
// Also you can copy variables from _variables.scss to _custom.scss
// to customize typography, spacing and other variables.
//
//


// Background color
$color-background: #444;
// For code, th
$color-background-over: rgba(255, 255, 255, .05);
// For selected area
$color-background-selected: rgba(255, 255, 255, .1);

// Border color
$color-border: #555;

// Text color
$color-text: #aaa;
$color-text-muted: #777;
// The link color
$color-text-link: hsl(50, 100%, 50%);

// For preview section
$smde-color-background-preview: #444;
// Image alt, HTML tag and attribute
$smde-color-text-tag: hsl(80, 50%, 50%);
```

Also you can copy variables from `_variables.scss` to `_custom.scss` to customize typography, spacing and other variables.

For more information, please checkout [SimpleMDE Theme Base](https://github.com/xcatliu/simplemde-theme-base)

---

Please feel free to give me any feedback, thanks!

**Comment by WesCossick** [comment]
Thanks for your work on this. More than likely, we'll be building native theme support into version 2, which (when I have more time) I'd like to begin working on. I'll use what you've developed as inspiration for that. In the meantime, people can use the work you've put together in your repository.
