### ISSUE TITLE
Get preview HTML programmatically

### ISSUE THREAD

**Issue by IonicaBizau** [sparksuite/simplemde-markdown-editor#499]
How to get the HTML which would be returned by the preview functionality?

**Comment by tommi-hirvonen** [comment]
var simplemde = new SimpleMDE(...)
simplemde.markdown(simplemde.value())

**Comment by WesCossick** [comment]
```JS
simplemde.options.previewRender("This is *example* Markdown");
```

**Comment by cory-haser** [comment]
FUTURE USERS: simplemde.togglePreview();
