### ISSUE TITLE
Wrong content in simplemde editor area

### ISSUE THREAD

**Issue by kiwiheretic** [sparksuite/simplemde-markdown-editor#502]
The simplemde widget is displaying wrong content in the editor area.  I believe I am using version 1.11.2.

When I examine the source of the web page using chrome I see the following in the source:

```
<textarea style="float:left; clear:left;" id="note-text" rows="20" name="note" placeholder="Type your note in here">&gt; NASB Jeremiah 9:24 but let him who boasts boast of this, that he understands and knows Me, that I am the LORD who exercises lovingkindness, justice and righteousness on earth; for I delight in these things,&quot; declares the LORD.  
&gt; NASB Jeremiah 9:23 Thus says the LORD, &quot;Let not a wise man boast of his wisdom, and let not the mighty man boast of his might, let not a rich man boast of his riches;  
&gt; NASB Jeremiah 9:24 but let him who boasts boast of this, that he understands and knows Me, that I am the LORD who exercises lovingkindness, justice and righteousness on earth; for I delight in these things,&quot; declares the LORD.  
</textarea>
 
<!---- snip -->

<script>
if (!mobilecheck()) {
    var simplemde = new SimpleMDE(
    { element: document.getElementById("note-text"),
	    autoDownloadFontAwesome: false,
		autosave : { 
            enabled: true,
            uniqueId: "cn1" 
        } 
    });
}

```

The editor does display and appear to work except for displaying completely the wrong content.  (Not that shown in the textarea html element.)  What I see is another note stored under a completely different database record.  Its as if the simplemde widget is caching old content.  However my web app doesn't use ajax for this so I wonder where it would be cached.  Does simplemde save content in cookies?

Is this because I have not configured this widget correctly to always get its initial value from the textarea?  If so how do I do this? 

If of any help my entire project is at https://github.com/kiwiheretic/logos-v2 under the dev branch and inside the cloud_notes/ folder.   

Thanks in advance.

**Comment by WesCossick** [comment]
It's most likely loading content from a previous autosave. Autosaved values won't be cleared unless the form is submitted, or you manually call:

```JS
simplemde.clearAutosavedValue();
```
