### ISSUE TITLE
Custom formating

### ISSUE THREAD

**Issue by OlegWock** [sparksuite/simplemde-markdown-editor#503]
Hello. I wrote some custom formating for marked.js:

=> Right aligned text
>=< cetner aligned text

How can I add it ti SimpleMDE?

**Comment by WesCossick** [comment]
SimpleMDE only supports standard Markdown and GitHub Flavored Markdown. There's no plans to add one user's custom formatting to it, as custom formatting isn't well suited for widespread use.
