### ISSUE TITLE
Setting value of simplemde textarea

### ISSUE THREAD

**Issue by FabianKoestring** [sparksuite/simplemde-markdown-editor#505]
Is there a way to set the content of simplmde markdown field per javascript? In the past we did something like ..

```js
var $field= $('textarea[name="simplemde"]').data('simplemde');
$field.value("iofhgihdfio ghodfihgoifdhgo");
```
I dont know what changed but now i will get `Uncaught TypeError: Cannot read property 'value' of undefined`.

**Comment by WesCossick** [comment]
See: https://github.com/NextStepWebs/simplemde-markdown-editor#getset-the-content

**Comment by FabianKoestring** [comment]
@WesCossick - Not at initialisation of simplemde. At any time. I have a button on an page. If you click that button i want to load some default text in some simplemde text fields. I cant find a way to do that.

**Comment by FabianKoestring** [comment]
I found a way!

```javascript
const $codemirror = $('textarea[name="myTeatxarea"]').nextAll('.CodeMirror')[0].CodeMirror;
$codemirror.getDoc().setValue("Blaaaaaaaaaaaaaaaaaaaaaaaaa");
```

**Comment by prvn3294** [comment]
@WesCossick  , while setting the value , if value is having HTML tags in it, its just displaying tags as string in editor.
is there any way to render HTML template while setting value.

**Comment by pezholio** [comment]
@FabianKoestring Thanks for this. This was super useful for writing integration tests when using simplemde 👍
