### ISSUE TITLE
Recursively encodes HTML entities

### ISSUE THREAD

**Issue by midwire** [sparksuite/simplemde-markdown-editor#506]
I really love this editor. It is the best Markdown editor that I have found! I have but one difficulty at this time, and I'm fairly certain it is a result of not configuring things properly.

It seems to encode HTML entities recursively. Example: I type in some text with a single-quote character, then save.

![chris_blackburn](https://cloud.githubusercontent.com/assets/178386/21991541/a513514a-dbd8-11e6-8aa7-cd4b6e95f022.jpg)

Then I edit the text, but the editor has encoded the single-quote as `&#39;`...

![chris_blackburn](https://cloud.githubusercontent.com/assets/178386/21991630/f5b9f18a-dbd8-11e6-8e91-f4df6f4a5826.jpg)

So, now, if I save this again, it encodes the ampersand, and so on...

![chris_blackburn](https://cloud.githubusercontent.com/assets/178386/21991687/2f4b6f32-dbd9-11e6-9050-ffc7ced5a0a1.jpg)

Can someone please explain what I'm doing wrong?

**Comment by midwire** [comment]
Apologies for posting this here. The problem was something else. Thanks again for an awesome Markdown editor.

**Comment by LukeXF** [comment]
I'm having the same issue, where was the problem?
