### ISSUE TITLE
bbcode editor

### ISSUE THREAD

**Issue by pherum** [sparksuite/simplemde-markdown-editor#507]
I'm sorry to write off topic.
I do not like the editor planned to work only with BB-codes?

**Comment by eNzyOfficial** [comment]
Seeing as it's a markdown editor (it's even part of the name), I wouldn't hold your breath 👎

**Comment by WesCossick** [comment]
SimpleMDE is focused on Markdown exclusively, but you're welcome to fork it and create a version for other formatting syntaxes.
