### ISSUE TITLE
I want to merge the optimized code into a new branch

### ISSUE THREAD

**Issue by unix** [sparksuite/simplemde-markdown-editor#508]
Thank you very much for your project. It is very good . I'm your loyal customer.

Recently I realized, When I need to understand how a function is implemented is very difficult, because there is only one file source, It's too long, reading is very difficult, and used some magic grammar. I thought for a long time,  and i think these problems do affect the robustness of the project, cause a lot of developers can not join, and missed a lot of good contributions.

Of course, i don't rewrite it with my own ideas, i don't have that mean. It took me 1 days to reconstruct the source code, and follow the original idea as much as possible. In grammar and abstract, I try to keep the following points:

- Do not change any function, do not add & delete function, test items to maintain normal operation.
- Delete some of the magic syntax from ES5, added some syntax sugar, make the code more concise.
- Separate different modules.
- As far as possible so that the function tends to immutable form.

Anyhow, i still have some problems. For example, what level of abstraction, whether it will affect the original way of thinking, performance optimization of a function... I hope the project will get better, But more details still want to follow the advice of the original developer.

I want to merge the optimized code into a new branch, and a long time to maintain and optimize them, and then create some tests for them, until the day that can merge into the main branch.

This is the address of fork: https://github.com/WittBulter/simplemde-markdown-editor
If possible, I will create a PR. (my english is not good, I hope you can understand this passage.)

**Comment by WesCossick** [comment]
Thanks for working on this. Unfortunately, this is something that I'd like my team to undertake, for version 2. I have a number of ideas for how to completely rewrite the editor from scratch, and it will depart from the current code style significantly. It's important, though, to maintain a high degree of quality and 100% backwards compatibility, which is why I plan to have it done in-house.

**Comment by WesCossick** [comment]
You are right, though, about the code not being very readable or maintainable. Hopefully we can fix that in the future with version 2!

**Comment by unix** [comment]
This is the open source community, not your user community. 
You look like swift.
