### ISSUE TITLE
More dev instructions in readme

### ISSUE THREAD

**Issue by fraserredmond** [sparksuite/simplemde-markdown-editor#51]
Can you add to the readme a block of html for running SME without using cdn.jsdelivr.net? Specifically for testing - I wasn't sure if all the source files were needed, and in what order (and TBH, was a bit too lazy to copy each file name and work it out :wink:).

Something like:

```
<script src="//your-domain-here.com/js/codemirror/codemirror.js"></script>
<script src="//your-domain-here.com/js/codemirror/overlay.js"></script>
<script src="//your-domain-here.com/js/codemirror/markdown.js"></script>
<script src="//your-domain-here.com/js/marked.js"></script>
<script src="//your-domain-here.com/js/spell-checker.js"></script>
<script src="//your-domain-here.com/js/typo.js"></script>
<script src="//your-domain-here.com/js/simplemde.js"></script>
```

**Comment by WesCossick** [comment]
The README is getting a bit long at this point, plus gulp.js handles compiling it for you. What you can do is look at the `gulpfile.js` file and look at the necessary order of the JS files. All JS files are needed.
