### ISSUE TITLE
Bower "main" value

### ISSUE THREAD

**Issue by noclat** [sparksuite/simplemde-markdown-editor#511]
Hi,

In the `bower.json`, the `main` value is set on sources instead of compiled scripts and styles. This causes an error when relying on a script like [bower-files](https://www.npmjs.com/package/bower-files) to automatically load vendor scripts.

```
Uncaught ReferenceError: require is not defined at simplemde.js:3
```

Could you please make it consistent with other common librairies (Bootstrap, jQuery, …), which `bower.json` mention their `dist/` files in `main` instead?

Thanks for building SimpleMDE!

**Comment by WesCossick** [comment]
Duplicate of #360
