### ISSUE TITLE
Post content as HTML code

### ISSUE THREAD

**Issue by AnTheMaker** [sparksuite/simplemde-markdown-editor#516]
I have a form in wich the textarea ist simpleMDE. But when I submit the form and echo the content of the textarea it is only the markup and not the HTML code. 
**How can i echo the textarea-input as HTML code?**

Here's my code:

index.html
```
<head>
<title></title>
<style>
.editor-preview h1,.editor-preview h2,.editor-preview h3,.editor-preview h4,.editor-preview h5{margin-bottom:10px;}.editor-preview h1{border-bottom:1px solid #ddd;}.editor-preview h1{border-bottom:1px solid #eee;}
</style>
</head>

<body>

<form action="test.php" method="POST">
<textarea id="demo1" name="con"># Test
**Just** some *Text*</textarea>
<input type="submit">
</form>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
<script>
	new SimpleMDE({
		element: document.getElementById("demo1"),
		spellChecker: false,
		autosafe: false,
		autofocus: true,
	});
	</script>
</body>
```

test.php
```
<?php
echo $_POST['con'];
?>
```

→ Output:
`# Test **Just** some *Text*`
and not
`<h1>Test</h1></br><b>Just</b> some <i>Text</i>`

**Comment by xolf** [comment]
Hey @PartyGuy01,

you need php to do this for you.

A libary like [Parsedown](http://parsedown.org/), will do it for you ;)

**Comment by WesCossick** [comment]
SimpleMDE is a Markdown editor. Therefore, you will receive Markdown when you post the form to your server.

**Comment by nerminba** [comment]
Use markdown it

https://github.com/markdown-it/markdown-it

before sending form to the server convert markdown with markdown-it to html code
