### ISSUE TITLE
Inline Javascript Code

### ISSUE THREAD

**Issue by newpain01** [sparksuite/simplemde-markdown-editor#521]
Hi,
Is there any way to embed inline JS in SimpleMDE, for example something like a block of JS for adsense or other ads?
Thanks

**Comment by TangentFoxy** [comment]
Well Markdown allows embedding HTML into it as part of the spec. As long as you're not blocking HTML content with SimpleMDE, there shouldn't be a problem.

**Comment by newpain01** [comment]
@Guard13007 Thanks for the answer, I figured it out a couple of days ago.

**Comment by sennyx** [comment]
Hello please can you share the solution

**Comment by TangentFoxy** [comment]
@sennyx Look up how to embed JavaScript in HTML. Markdown allows embedding HTML, therefore you can embed JavaScript in Markdown the same way you do with HTML.
