### ISSUE TITLE
Incorrect link parsing in preview mode

### ISSUE THREAD

**Issue by mertkahyaoglu** [sparksuite/simplemde-markdown-editor#528]
Hi everyone! I'm the core maintainer of Jekyll Admin which makes use of SimpleMDE editor for its content management. Huge thanks for this project btw ❤️ 

We got an issue yesterday about invalid link parsing in preview mode. Here is the [issue](https://github.com/jekyll/jekyll-admin/issues/306).

Basically if you have parenthesis in the url, the rendered link becomes invalid.

For example;

`[foo](https://en.wikipedia.org/wiki/Pointer_(computer_programming)) bar`

results in;

`foo) bar`

**Comment by TangentFoxy** [comment]
This is a standard problem with MarkDown as far as I understand it. You just can't use that syntax with a link that ends in a `)`. Either that or it's extremely common. I see it happen all the time, and use:

```
[foo][1]

[1]: https://en.wikipedia.org/wiki/Pointer_(computer_programming)
```

to get around it.

**Comment by WesCossick** [comment]
It seems that CodeMirror handles the parsing correctly while editing. However, [Marked](https://github.com/chjj/marked) is not parsing it correctly for previewing. Since we depend on this library for SimpleMDE, an issue would need to be submitted with their repository.
