### ISSUE TITLE
Why can't I get this to work in Microsoft Edge or on an iPhone?

### ISSUE THREAD

**Issue by ajtruckle** [sparksuite/simplemde-markdown-editor#533]
Thank you.

**Comment by WesCossick** [comment]
This type of question may be better suited for StackOverflow.

**Comment by ajtruckle** [comment]
It is part of a plugin for mantisbt. Won't work.

Sent from my iPhone

On 1 Mar 2017, at 22:36, Wes Cossick <notifications@github.com<mailto:notifications@github.com>> wrote:


This type of question may be better suited for StackOverflow.
