### ISSUE TITLE
TypeError: undefined is not an object (evaluating 't.value')

### ISSUE THREAD

**Issue by travisjtodd** [sparksuite/simplemde-markdown-editor#54]
I tried out the very basic setup of this plugin but am getting this error:

![screen shot 2015-08-14 at 14 44 49](https://cloud.githubusercontent.com/assets/47908/9274123/27893f62-4293-11e5-9e87-99eef99b2b5e.png)

Here's what the code looks like:

```
    <link rel="stylesheet" media="screen" href="//maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
    <link rel="stylesheet" media="screen" href="//cdn.jsdelivr.net/simplemde/latest/simplemde.min.css" />
    <script src="//cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
    <script>
      var simplemde = new SimpleMDE();
      simplemde.render();
    </script>
```

**Comment by WesCossick** [comment]
Do you have any `<textarea></textarea>` on that page? You'll need to add at least one `<textarea></textarea>` to the page.

**Comment by travisjtodd** [comment]
Yes, two in fact.

**Comment by WesCossick** [comment]
Can you create a JSFiddle that replicates the issue?

**Comment by travisjtodd** [comment]
Sorry. Just getting back to this project. Made a JSFiddle: http://jsfiddle.net/tpdzbhtp/

**Comment by danabrey** [comment]
The JSFiddle is erroring when trying to fetch simplemde.min.js as it is missing the https:// - seems fine here: http://jsfiddle.net/tpdzbhtp/1/

**Comment by travisjtodd** [comment]
I was basing it off the explanation in the readme that specified this:

```
<script src="//cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
```

**Comment by danabrey** [comment]
The link to the javascript in [this JSFiddle](http://jsfiddle.net/tpdzbhtp/) doesn't include the protocol-relative `//`. If you change the source link to `//cdn.jsdelivr.net/simplemde/latest/simplemde.min.js`, [it's happy](https://jsfiddle.net/tpdzbhtp/2/).

**Comment by WesCossick** [comment]
@danabrey is correct. If you look closely, the `//` is missing from the `simplemde.min.js` script in the JSFiddle you linked to.
