### ISSUE TITLE
Lists rendered are "previewed" ok even if there is no empty line before them

### ISSUE THREAD

**Issue by vioan** [sparksuite/simplemde-markdown-editor#543]
I am using: 
https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js

source code in editor:
https://www.dropbox.com/s/nnd8r08awgyacct/Screenshot%202017-03-09%2021.18.34.png?dl=0

preview:
https://www.dropbox.com/s/2zv1lhdz4eyorng/Screenshot%202017-03-09%2021.19.17.png?dl=0

And if generated markdown has to be saved in database or rendered with a different markdown editor is not showing the lists correctly, see here:

https://www.dropbox.com/s/yi3pg9bx7vfhtu5/Screenshot%202017-03-09%2021.20.59.png?dl=0

So, or the editor should add an empty line before the list starts or the preview should show the correct rendering (I mean with the bad formatted list) and then the user knows that is not correct formatted markdown.

**Comment by WesCossick** [comment]
Sounds like the renderer you're using later has some differences with the renderer we use with SimpleMDE. You'll need to choose a renderer on your end that matches the renderer for SimpleMDE.
