### ISSUE TITLE
Looks like simpleMDE is not compatible with django_markdown

### ISSUE THREAD

**Issue by linghu-chong** [sparksuite/simplemde-markdown-editor#55]
for example simpleMDE support ```,
however django_markdown does not support that.

it looks django_markdown used a old markdown grammer. 
What version of markdown is simpleMDE using?

**Comment by linghu-chong** [comment]
the issue is, the ``` will be translated to <  code  >  <  /  code > which is not well displayed in a lot of css styles. it should be translated to < pre  >  <  /pre  >

**Comment by WesCossick** [comment]
SimpleMDE uses GitHub Flavored Markdown, where ``` delineates a code block like so:

```
// Code
```

You can specify a different mode by modifying the code on these lines: https://github.com/NextStepWebs/simplemde-markdown-editor/blob/master/src/js/simplemde.js#L525-L526
