### ISSUE TITLE
Multiple editors on one page with spell checker enabled consume a lot of memory

### ISSUE THREAD

**Issue by jetmind** [sparksuite/simplemde-markdown-editor#56]
I've run into this ~3 weeks ago in 1.4.0, but it seems like it was not been fixed.

Browser tab eats ~1Gb of memory on a page with ~10 of editors with spell checker enabled and it grows the more editors on a page you have.

I didn't look very closely into that, but with profiling enabled in Chrome I see a lot of calls to `Typo._parseDIC`. My understanding is that every editor fetches it's own spell checking dictionary, so memory consumption grows linearly with the number of editors. They should share one dictionary, probably.

**Comment by WesCossick** [comment]
Thanks for catching this. I've fixed it with 438b3ef.
