### ISSUE TITLE
Impossible to escape character in link

### ISSUE THREAD

**Issue by ghost** [sparksuite/simplemde-markdown-editor#573]
Hi everybody !

I'm sorry to disturb you, but I have a little problem with the editor. I'm trying to put a link in my text, but there is a special character which I can't escape. The character is `)`.
This is my text:
```
*Source: [Wikipédia](http://fr.wikipedia.org/wiki/Java_(langage\)#Types_de_compilations)*
```
And I get this:
_Source: Wikipédia#Types_de_compilations)_

Normally, the `)` after langage is escaped. But apparently, the editor doesn't understand that.
Maybe I'm doing something wrong (I have supposed that '\\' is used to escape character) ?

Thank you very much for your help.

**Comment by cbaxter** [comment]
@georgesben One workaround would be to encode the ( and ) characters as %28 and %29.

**Example**
`[Wikipédia](http://fr.wikipedia.org/wiki/Java_%28langage\%29#Types_de_compilations)`

Would prefer to escape with a `\` as one would expect, but at least provides an option...

**Comment by ghost** [comment]
Great solution !

Thank you very much ! =D
