### ISSUE TITLE
Render the html

### ISSUE THREAD

**Issue by johndodev** [sparksuite/simplemde-markdown-editor#574]
Hello,

the editor works well, I can save markdown content in my database, but there is no documentation about render the html of that content.

I assume I can do it with this library, which do it on the editor itself, but is there a good way to do it ?

**Comment by im-here** [comment]
you can use this:
````
var simplemde = new SimpleMDE();

simplemde.markdown("This is *example* Markdown");
// or
simplemde.options.previewRender("This is *example* Markdown");
````

**Comment by johndodev** [comment]
Thanks !

**Comment by johndodev** [comment]
Hm, actually it render an editor on the page. I will looking for another tool.

**Comment by im-here** [comment]
yes,it will render an editor on the page. but you can put the ``textarea``  in a div which ``display=none``,and then call ``simplemde.toTextArea() ``.
but i think it's not the best way. so i use third library.
