### ISSUE TITLE
Custom preview source

### ISSUE THREAD

**Issue by jetmind** [sparksuite/simplemde-markdown-editor#58]
Add option to specify a callback, which will return rendered markdown instead of using default `editor.constructor.markdown`

It can be useful in cases when editor is used with richer markdown superset, than it supports by default. For example, callback can make request to a server, which can render this richer subset properly and display that.

We're using this approach already in [allura](https://github.com/apache/allura/blob/master/Allura/allura/lib/widgets/resources/js/sf_markitup.js#L95-L149) but it requires copy&pasting `togglePreview` method, which requires synchronization whenever new version is released.

Also, events or custom callbacks for preview open/close events would be useful, e.g. to add some custom styles to the editor.

**Comment by WesCossick** [comment]
These sound like good ideas. Would you want to create a PR that features these changes?
