### ISSUE TITLE
convert to md

### ISSUE THREAD

**Issue by clayclayclay** [sparksuite/simplemde-markdown-editor#585]
Hi, all.
When I write some messages with this js plugin, I want to convert the html to md?
Just like the:
  <h1>example title<h1>
 # example title

**Comment by dorelljames** [comment]
I believe this is meant to be used that you write in Markdown. So with your question, you can bind in a function to convert to md the contents of this on change or on save. Up to you!

**Comment by clayclayclay** [comment]
@dorelljames  Hi, I understand your meaning.
I just want to know whether the plugin support the function that convert html to md?

**Comment by dorelljames** [comment]
Rich formatting pasting and auto-translating to markdown is not supported so I doubt it supports what you need.

**Comment by clayclayclay** [comment]
@dorelljames okay
