### ISSUE TITLE
Show tool bar in side by side view

### ISSUE THREAD

**Issue by jfraboni** [sparksuite/simplemde-markdown-editor#600]
Anyway to show the toolbar in the side by side view?

**Comment by boomtothemoon** [comment]
There is toolbar as a default when you toggle side by side view

**Comment by jfraboni** [comment]
@boomtothemoon thanks, I see what our issue is then, the Bootstrap header for the site has a z-index greater than that of the side by side toolbar.  Fixed by overriding the rule for the side by side toolbar. like so:

```
.editor-toolbar.fullscreen {
  z-index: <a number higher than your bootstrap header>;
}
```
