### ISSUE TITLE
How to integrate with webpack?

### ISSUE THREAD

**Issue by slince** [sparksuite/simplemde-markdown-editor#621]
## What i did:

```js

import SimpleMDE  from 'simplemde';

new SimpleMDE($('#demo')[0]);
```

## What happed:
Editor can be rendered, but it seems lost the css style.

**Comment by JoshTheDerf** [comment]
@slince I know you asked almost a month ago, but you can include the css by importing the CSS for SimpleMDE directly, as shown below. Works like a charm.

```javascript
import SimpleMDE from 'simplemde';
import 'simplemde/dist/simplemde.min.css';

...
```

**Comment by slince** [comment]
@Tribex  Thanks, i have done like that. The developer seems very busy...

**Comment by xwchris** [comment]
helped me!

**Comment by slince** [comment]
@xwchris    按照二楼说的做就可以了，主动引入css文件
