### ISSUE TITLE
Unusable layout when upgrading Bootstrap 3=>4

### ISSUE THREAD

**Issue by chandler37** [sparksuite/simplemde-markdown-editor#649]
Thank you for SimpleMDE. Works great for me but I'm trying to upgrade from the latest Bootstrap 3 to the current alpha of Bootstrap 4 and having trouble. You can see on the fiddle below that the layout is unusable:

https://jsfiddle.net/rsjaeaps/1

What needs to change?

**Comment by chandler37** [comment]
I wasn't using the grid properly. Nevermind.

**Comment by punitganshani** [comment]
what was the fix?
