### ISSUE TITLE
Math mode

### ISSUE THREAD

**Issue by Silverutm** [sparksuite/simplemde-markdown-editor#704]
Is there a way to display equations?

> $x^2 + x_1 + 1 = 4^3$

**Comment by kddelosreyes** [comment]
Another concern is we cannot use other math symbols like "element of", "there exist", "subset", etc.

**Comment by kddelosreyes** [comment]
@Silverutm you can use <sub></sub> and <sup></sup> as an alternative.

**Comment by CompSciRocks** [comment]
Any chance there's an update on this, or maybe a similar project that does support MathJax / KaTex / LaTex?  This project looks 99% perfect, except for math support, for something I'm working on.

**Comment by Silverutm** [comment]
What I did is
Download the image generated by http://quicklatex.com/  with no background 
and then displayed it with 
`<img src="dropbox or the place the image is save" style="display: block; margin-left: auto; margin-right: auto;" />`

Dont recomend using the url generated by quiklatex as img src because it disappears after a few weeks

**Comment by Silverutm** [comment]
The html code is inserted between the markdown, works perfectly
