### ISSUE TITLE
Option to force double line break?

### ISSUE THREAD

**Issue by jesseleite** [sparksuite/simplemde-markdown-editor#71]
![Example screencast](http://g.recordit.co/7FUyrjpS8S.gif)

I think this is rarely desirable from an end user standpoint.  If the markdown standard itself doesn't support single line breaks, could we have an option to force a double line breaks when a user presses enter?

Assuming it's an optional opt-in / opt-out thing, the only downside I can think of is removing these line breaks will require two backspace presses... though I suppose you could get clever there as well so that it's one enter press to force double line break, and one backspace press to delete double line break (if one is detected).

Your thoughts on this?

**Comment by WesCossick** [comment]
I have never liked this behavior of Markdown, luckily it looks like Marked has an option to enable GFM style line breaks. I'll see if this option will work.

**Comment by JesseLeite** [comment]
@WesCossick awesome thanks. At worst, if you want user to have full control, it could be implemented as an opt-in thing.  I still think single line breaks are rarely desirable the way most Markdown standards handle them.

**Comment by jesseleite** [comment]
@WesCossick: I'm confused because GFM handles single line breaks the same way.

![GFM](http://g.recordit.co/Og04jTCwLB.gif)

Also, don't you use Marked for preview pane parsing only?  This doesn't help if we're using a different GFM or Commonmark parser (not Marked) in our front end.  My suggestion is to force double line break in the editor, so that the user cannot accidentally use single line breaks.  ...or at least implement an opt-in setting to force double line breaks when user hits enter.

**Comment by WesCossick** [comment]
SimpleMDE uses GFM by default, so using GFM line breaks would be a desirable default, with the option to disable this. GFM line breaks can be seen in the commenting system, not their file editor.

The only previewing SimpleMDE handles is the preview pane, which does use Marked. The Markdown parser the developer chooses will need to follow GFM standards, which supports single line breaks. If the developer chooses Commonmark or another non-GFM parser, then many areas will be inconsistent.

A double line break would not work in most situations, i.e. at the end of any line that isn't a block of text. Bullet points, headers, tables, code blocks, etc. need single line breaks.

**Comment by jesseleite** [comment]
Hmm interesting,

> GFM line breaks can be seen in the commenting system, not their file editor.

Ha, it's confusing that GitHub uses a different markdown standard from readme to comments.  Line breaks are also not as clearly defined [here](https://help.github.com/articles/github-flavored-markdown/) as they could be.

> A double line break would not work in most situations, i.e. at the end of any line that isn't a block of text.  Bullet points, headers, tables, code blocks, etc. need single line breaks.

Didn't think of this, good point.  That said, you could use the parser to detect where the user is trying to line-break from a normal block of text, versus lists, tables, etc.  I'm beginning to think that this would need to be opt-in, not a default option.  Though would still be nice to opt-in assuming it were smart enough to know where the user is trying to line break from.

My suggestion is getting a lot more complicated than I originally anticipated :P

**Comment by jesseleite** [comment]
> SimpleMDE uses GFM by default

Maybe this could be mentioned in your readme?  Also on that note, is it possible to switch out the parser for a Commonmark parser?

I sound like I'm complaining a lot here... really not, your package is awesome!  These are all just suggestions :)

**Comment by WesCossick** [comment]
The next version of SimpleMDE will support single line breaks, which is consistent with how the editor displays them before the preview button is clicked, and consistent with GFM. I also think this is the most intuitive format, especially for non-technical users (the target audience).

I also added a mention that SimpleMDE uses GFM to the README, though there was a great place to mention it prominently. It should be fairly obvious though if you are familiar with the differences.

I do not currently have intentions of allowing the ability to switch out the parser, though. It could be added in the future, but I believe GFM is much better suited for the target audience. Plus it's more powerful in general.

**Comment by jesseleite** [comment]
> will support single line breaks [...] think this is the most intuitive format, especially for non-technical users (the target audience)

100% agree on this.  I've been using Commonmark on a few projects, and it's served me well.  Like you, I hate how it handles single line breaks though.
