### ISSUE TITLE
Travis Config - Insecure API Key

### ISSUE THREAD

**Issue by prageeth** [sparksuite/simplemde-markdown-editor#722]
@WesCossick Looking at the travis config, shouldn't the api key be hidden and used via environmental variable? This is opening up for insecure publishing.

**Comment by atodorov** [comment]
@prageeth the value is marked with `secure: xxxx` and I think this is the encrypted value not the plain/text one so no direct exposure, see https://docs.travis-ci.com/user/environment-variables/#defining-encrypted-variables-in-travisyml

**Comment by prageeth** [comment]
@atodorov Thanks for the explanation, it was my mistake. Yes, you're right and it makes sense. Thanks!
