### ISSUE TITLE
Dynamically created editors

### ISSUE THREAD

**Issue by CrystalShardz** [sparksuite/simplemde-markdown-editor#754]
Is there a way to make a dynamically generated textarea a simplemde object? I.E i click a button and it adds a new textarea element that is enabled as a simplemde input and can do this multiple times.

thanks

**Comment by CrystalShardz** [comment]
I figured this out. I needed to put initialisation into my event handler to effectively create a new object on click.

**Comment by sudarshaana** [comment]
Can you please share the code snippet?

**Comment by johnemmatty** [comment]
@CrystalShardz , Can you please share this script?
