### ISSUE TITLE
[QUESTION] Change caret color

### ISSUE THREAD

**Issue by nigellima** [sparksuite/simplemde-markdown-editor#765]
Is it possible to change the caret color?

I've tried to use new css atribute `caret-color: red;` but it does not affect it and it's still black

Thanks in advance

**Comment by luckyshot** [comment]
I know this issue is closed but for anyone else with this question, this is the solution:

```CSS
.CodeMirror-cursor {
  border-color: white;
}
```

Since the cursor is essentially a `<div>`, you can even alter other properties such as the width: `border-left-width: 2px;`
