### ISSUE TITLE
How to programmatically focus SimpleMDE?

### ISSUE THREAD

**Issue by Rukenshia** [sparksuite/simplemde-markdown-editor#773]
Hello,

I want to focus my SimpleMDE through a keyboard shortcut. I used a simple textarea before and could just call `myTextarea.focus()` to switch focus. How does this work with SimpleMDE?

Thanks!

**Comment by Rukenshia** [comment]
Works using `simplemde.codemirror.focus()` 😄

**Comment by xfoscarz** [comment]
thanks!
