### ISSUE TITLE
Better element option behavior

### ISSUE THREAD

**Issue by WesCossick** [sparksuite/simplemde-markdown-editor#79]
> @WesCossick, I agree, if no element key is explicitly set in options array. But but if element is explicitly set in options, that suggests the user does not want default behaviour. If the user then makes an error selecting the element (as I did), there's no error in console to reflect erroneous element selector. Might I suggest a small tweak?
> 
> If no element key is explicitly set in options, revert to your default (first textarea in DOM).
> If an explicit element key is set in options, override default (but throw error in console if user's selector is erroneous).
> 
> —@JesseLeite

**Comment by jesseleite** [comment]
I appreciate this, thanks man :)

**Comment by WesCossick** [comment]
Fixed.
