### ISSUE TITLE
Disable heading, img and list

### ISSUE THREAD

**Issue by lubiah** [sparksuite/simplemde-markdown-editor#807]
_Hello_
I wanted to know if it is possible to exclude all other features and use only bold, italic and underline

**Comment by Gigamick** [comment]
Yes this is possible, as per the documentation. Add these options.

```
toolbar: ["bold", "italic", "underline"],
```

**Comment by bramaudi** [comment]
> Yes this is possible, as per the documentation. Add these options.
> 
> ```
> toolbar: ["bold", "italic", "underline"],
> ```

I'm looking for something similar, but i need to disable everything not just hide some the toolbar icon

**Comment by ghost** [comment]
i have same issue, do u solve issue ?
