### ISSUE TITLE
con't preview

### ISSUE THREAD

**Issue by l5769389** [sparksuite/simplemde-markdown-editor#808]
![image](https://user-images.githubusercontent.com/26296535/103777702-3d4bcd00-506c-11eb-9234-e8c2d7a5a4e2.png)

preview is not effect,this is my code in vue3.0

` const simplemde = new SimpleMDE({
        autofocus: true,
        autosave: {
          enabled: true,
          uniqueId: "editor01",
          delay: 1000,
        },
        blockStyles: {
          bold: "__",
          italic: "_"
        },
        element:document.getElementById("editor"),
        forceSync: true,
        hideIcons: ["guide", "heading"],
        indentWithTabs: false,
        initialValue: "SimpleMDE Dome",
        insertTexts: {
          horizontalRule: ["", "\n\n-----\n\n"],
          image: ["![](http://", ")"],
          link: ["[", "](http://)"],
          table: ["", "\n\n| Column 1 | Column 2 | Column 3 |\n| -------- | -------- | -------- |\n| Text     | Text      | Text     |\n\n"],
        },
        lineWrapping: false,
        parsingConfig: {
          allowAtxHeaderWithoutSpace: true,
          strikethrough: false,
          underscoresBreakWords: true,
        },
        placeholder: "placeholder",
        promptURLs: true,
        renderingConfig: {
          singleLineBreaks: false,
          codeSyntaxHighlighting: true,
        },
        shortcuts: {
          drawTable: "Cmd-Alt-T"
        },
        showIcons: ["code", "table"],
        spellChecker: false,
        status: ["autosave", "lines", "words", "cursor", {
          className: "keystrokes",
          defaultValue: function(el) {
            this.keystrokes = 0;
            el.innerHTML = "0 Keystrokes";
          },
          onUpdate: function(el) {
            el.innerHTML = ++this.keystrokes + " Keystrokes";
          }
        }],
        styleSelectedText: false,
        tabSize: 4,

      });`

**Comment by l5769389** [comment]
I solved it by:


<template >
  <div class="container">
    <textarea name="" rows="" cols="" id="editor"></textarea>
  </div>
</template>

<style scoped>
@import "~simplemde/dist/simplemde.min.css";
</style>
<script lang="ts">
import {  defineComponent,onMounted } from 'vue';
import SimpleMDE from 'simplemde/dist/simplemde.min.js'
export default defineComponent({
   name: 'App',
  setup(){
   onMounted(()=>{
     var simplemde = new SimpleMDE({
       autofocus: true,
       autosave: {
         enabled: true,
         uniqueId: "editor01",
         delay: 1000,
       },
       blockStyles: {
         bold: "__",
         italic: "_"
       },
       element: document.getElementById("editor"),
       forceSync: true,
       hideIcons: ["guide", "heading"],
       indentWithTabs: false,
       initialValue: "SimpleMDE Dome",
       insertTexts: {
         horizontalRule: ["", "\n\n-----\n\n"],
         image: ["![](http://", ")"],
         link: ["[", "](http://)"],
         table: ["", "\n\n| Column 1 | Column 2 | Column 3 |\n| -------- | -------- | -------- |\n| Text     | Text      | Text     |\n\n"],
       },
       lineWrapping: false,
       parsingConfig: {
         allowAtxHeaderWithoutSpace: true,
         strikethrough: false,
         underscoresBreakWords: true,
       },
       placeholder: "placeholder",
       promptURLs: true,
       renderingConfig: {
         singleLineBreaks: false,
         codeSyntaxHighlighting: true,
       },
       shortcuts: {
         drawTable: "Cmd-Alt-T"
       },
       showIcons: ["code", "table"],
       spellChecker: false,

       status: ["autosave", "lines", "words", "cursor", {
         className: "keystrokes",
         defaultValue: function(el) {
           this.keystrokes = 0;
           el.innerHTML = "0 Keystrokes";
         },
         onUpdate: function(el) {
           el.innerHTML = ++this.keystrokes + " Keystrokes";
         }
       }], // Another optional usage, with a custom status bar item that counts keystrokes
       styleSelectedText: false,
       tabSize: 4,
       //toolbar: flase,
       //toolbarTips: false,
     });
   })
  }
});
</script>

**Comment by RobertBrunhage** [comment]
Hey @l5769389 could you elaborate on what fixed it exactly? This is really hard to read when you haven't used the formatting
