### ISSUE TITLE
Cannot run simple demo

### ISSUE THREAD

**Issue by sigmasoldi3r** [sparksuite/simplemde-markdown-editor#811]
Attempting to load a simple HTML document:

```html
  <div id="MyID"></div>
  <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
  <script>
    const simplemde = new SimpleMDE({ element: document.getElementById("MyID") });
  </script>
```

No other Javascript frameworks are present, and using the latest Firefox version.

But console displays an `Uncaught TypeError: can't access property "first", t is undefined`.

**Comment by pixlmint** [comment]
@sigmasoldi3r You need to use textareas. So replace your `div` with `textarea`.

**Comment by sigmasoldi3r** [comment]
It solves the issue! Thanks! 😃
