### ISSUE TITLE
previewRender can't handle async functionality

### ISSUE THREAD

**Issue by WesCossick** [sparksuite/simplemde-markdown-editor#85]
Either make a hybrid function or add a new option for handling async.

**Comment by WesCossick** [comment]
@brondsem, check out the latest commit and README in the development branch. The function is now a hybrid function that supports async behavior too. Let me know your thoughts.

**Comment by brondsem** [comment]
Thanks, that works well for me and its an elegant way to do it.

**Comment by WesCossick** [comment]
Excellent, thanks for the initial work on it!
