### ISSUE TITLE
Syntax highlighting for code blocks

### ISSUE THREAD

**Issue by drmuey** [sparksuite/simplemde-markdown-editor#86]
First off, excellent editor field, thanks!

It'd be smashing if the code blocks could be syntax highlighted.

FWiW, Git hub uses https://github.com/github/linguist

**Comment by Xarcell** [comment]
I would also like to see this.

**Comment by drmuey** [comment]
In my local copy this works like champ via `marked.setOptions`:

``` js
    highlight: function (code) {
        return hljs.highlightAuto(code).value;
    }
```

Could be as simple as setting that if highlight.js is loaded (i.e. wrapped in an if `window.hljs`)

**Comment by WesCossick** [comment]
I plan to add this to v1.7.1, the next version coming out.

**Comment by WesCossick** [comment]
Added in v1.7.2 with this commit 443a58cc2811b571b9256db8bcd473ff1dd106ee

**Comment by drmuey** [comment]
Excellent, thanks!

**Comment by Xarcell** [comment]
Thanks.
