### ISSUE TITLE
toolbar missing buttons

### ISSUE THREAD

**Issue by drmuey** [sparksuite/simplemde-markdown-editor#87]
Greetings!

This is probably something I am doing wrong but am stuck ATM, help!

When I define toolbar like like this:

`toolbar: ["bold", "italic", "strikethrough", "heading", "|", "code", "quote", "unordered-list", "numbered-list", "|", "link", "image", "horizontal-rule", "|", "preview", "side-by-side", "guide"]`

strikethrough, numbered-list, and side-by-side are blank. (when moused over they look like what the red arrow is pointing to in the screenshot, when clicked on nothing happens)

There is nothing in console for any of the process.

![screenshot of problem](http://imgur.com/9azGeiQ.png)

Instantiation HTML:

``` html
<textarea id="comment-1" form="form-1441391701-0" name="comment" class="form-control" placeholder="" >initial content</textarea>
<script type="text/javascript">
    $( document ).ready(function() {
        var simplemde = new SimpleMDE({ 
            element: $("#comment-1")[0],
            toolbar: ["bold", "italic", "strikethrough", "heading", "|", "code", "quote", "unordered-list", "numbered-list", "|", "link", "image", "horizontal-rule", "|", "preview", "side-by-side", "guide"]
        });
        simplemde.render(); 
    });
</script>
```

**Comment by WesCossick** [comment]
I was notified earlier today that `numbered-list` should really be `ordered-list`, and it was mis-documented. It's been corrected now in the development branch and will be released with the upcoming v1.7.1. Regarding the two other buttons, it's possible jsDelivr hasn't updated the `latest` URL to 1.7.0, when `strikethrough` and `side-by-side` were released. To check, open the source code for the `.min.js` file and check the top comment to see if it's 1.7.0 or not.

**Comment by drmuey** [comment]
thanks! 

Changing `numbered-list` to `ordered-list` did not help it to show up. Should it have or will it need to wait until the change you mentioned above?

`strikethrough` and `side-by-side` showed up about an hour later, probably caching or some other gremlin :)

**Comment by drmuey** [comment]
ICIH, the missing button is `<a class="undefined"></a>` when I "Inspect Element" in Chrome.

**Comment by drmuey** [comment]
… and `ordered-list` showed up ;) must be the same caching stuff as the other two, thanks!

**Comment by WesCossick** [comment]
Probably a caching issue. jsDelivr can take a few days to update, and we've been pushing releases frequently recently.
