### ISSUE TITLE
Styling issue with fullscreen and side-by-side mode.

### ISSUE THREAD

**Issue by jesseleite** [sparksuite/simplemde-markdown-editor#88]
Notice the background showing through under the toolbar icons.

PS. The new side-by-side fullscreen mode is amazing!  Thank you guys!

![example](http://b3.ms/a8XAj8GzMBDx)

**Comment by WesCossick** [comment]
Yep, that's an issue. It'll be corrected in the next release.

**Comment by jesseleite** [comment]
👍
