### ISSUE TITLE
2-3 errors (from recently added features)

### ISSUE THREAD

**Issue by fraserredmond** [sparksuite/simplemde-markdown-editor#91]
I'm getting the error:

```
Uncaught TypeError: Cannot read property 'className' of null
```

In the last line of this block:

```
SimpleMDE.prototype.createSidebyside = function() {
    var cm = this.codemirror;
    var wrapper = cm.getWrapperElement();
    var preview = wrapper.nextSibling;

    if(!/editor-preview-side/.test(preview.className)) {
```

I have the old/normal preview enabled, and when I click it, I get this error:

```
Uncaught TypeError: Cannot read property 'singleLineBreaks' of undefined
```

(I don't have `singleLineBreaks` defined in the options when I initialize the object.)

Possible causes, or steps to reproduce:
- I don't have the side-by-side enabled in the toolbar buttons.
- The textarea I'm targeting does not have any siblings.
- I'm getting SME from cdn.jsdelivr.net

I'm not sure if it's related, or a separate problem, but I have a `change` event defined that used to work, but is no longer firing (apart from that and preview, everything else seems to work fine.)

**Comment by LulzAugusto** [comment]
Same problem here

**Comment by WesCossick** [comment]
I'm not able to reproduce these errors, can you create a JSFiddle that does? Ideally, it would exemplify all three bugs.
