### ISSUE TITLE
Pass through mode options

### ISSUE THREAD

**Issue by WesCossick** [sparksuite/simplemde-markdown-editor#94]
Do so using the new `parsingConfig` option to keep SimpleMDE's configuration as clean as possible, without relying on users knowing CodeMirror's details. To do:
- [x] Fully document the available options in the README
- [x] Fully test the implementation

**Comment by WesCossick** [comment]
Currently `fencedCodeBlocks` does not work correctly (issue submitted with CodeMirror). Otherwise, this is complete.

**Comment by thanhdinhit** [comment]
kllkl**kllk**
