### ISSUE TITLE
A BUG when using Toggle side to side and Toggle fullscreen

### ISSUE THREAD

**Issue by Kilerd** [sparksuite/simplemde-markdown-editor#99]
when using it, I found a bug,(I found thhat this bug is also on your demo )
this is my code

``` html
<script>
var simplemde = new SimpleMDE({
    element: document.getElementById("note"),
    spellChecker:false,
    tabsize:4,
});

</script>
```

So, the bug is:

when I press `Toggle Fullscreen` on the toolbar
Type something or nothing,(it's OK)
then, if I press `Toggle Fullscreen` again to return common status, the bug would not appear.
But if I press `Esc` to quit, Something ineresting happen, I cann't type to show you what happen, JUST TRY BY YOURSELF.
It also appear when using `Esc` in `Toggle side to side`

I think you forget to code about this way to quit form `Toggle Fullscreen` and `Toggle side to side`

I hope you can fix the bug(In my opinion this is a bug)

This Markdown Editor is the best one I have ever used. Hope that it can be supported.

I'm sorry that I am just a Pythonista, I cann't fix it by myself with my poor javascript.

Only thing I can do is to use it and finding more bug to perfect it together.

**Comment by WesCossick** [comment]
Thanks for identifying this bug. In summary:

When in fullscreen mode, if the user presses `esc`, the toolbar remains where it is (stuck at the top), while the editor returns to its correct size.
